spring:
  main:
    allow-bean-definition-overriding: true #fix bean 重名
  application:
    name: zipkin
server:
  port: 23010
management:
  metrics:
    web:
      server:
        auto-time-requests: false #fix IllegalArgumentException