// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: baseMessage.proto

package com.topsec.mobiapi.proto;

public final class BaseMessage {
  private BaseMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PageContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.topsec.mobiapi.proto.PageContent)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *每页数据量大小
     * </pre>
     *
     * <code>int32 pageSize = 1;</code>
     */
    int getPageSize();

    /**
     * <pre>
     *当前页码
     * </pre>
     *
     * <code>int32 currPage = 2;</code>
     */
    int getCurrPage();

    /**
     * <pre>
     *总记录数
     * </pre>
     *
     * <code>int32 totalCount = 3;</code>
     */
    int getTotalCount();

    /**
     * <pre>
     *总页数
     * </pre>
     *
     * <code>int32 totalPage = 4;</code>
     */
    int getTotalPage();
  }
  /**
   * <pre>
   *分页查询条件
   * </pre>
   *
   * Protobuf type {@code com.topsec.mobiapi.proto.PageContent}
   */
  public  static final class PageContent extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.topsec.mobiapi.proto.PageContent)
      PageContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PageContent.newBuilder() to construct.
    private PageContent(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PageContent() {
      pageSize_ = 0;
      currPage_ = 0;
      totalCount_ = 0;
      totalPage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PageContent(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              pageSize_ = input.readInt32();
              break;
            }
            case 16: {

              currPage_ = input.readInt32();
              break;
            }
            case 24: {

              totalCount_ = input.readInt32();
              break;
            }
            case 32: {

              totalPage_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_PageContent_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_PageContent_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.topsec.mobiapi.proto.BaseMessage.PageContent.class, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder.class);
    }

    public static final int PAGESIZE_FIELD_NUMBER = 1;
    private int pageSize_;
    /**
     * <pre>
     *每页数据量大小
     * </pre>
     *
     * <code>int32 pageSize = 1;</code>
     */
    public int getPageSize() {
      return pageSize_;
    }

    public static final int CURRPAGE_FIELD_NUMBER = 2;
    private int currPage_;
    /**
     * <pre>
     *当前页码
     * </pre>
     *
     * <code>int32 currPage = 2;</code>
     */
    public int getCurrPage() {
      return currPage_;
    }

    public static final int TOTALCOUNT_FIELD_NUMBER = 3;
    private int totalCount_;
    /**
     * <pre>
     *总记录数
     * </pre>
     *
     * <code>int32 totalCount = 3;</code>
     */
    public int getTotalCount() {
      return totalCount_;
    }

    public static final int TOTALPAGE_FIELD_NUMBER = 4;
    private int totalPage_;
    /**
     * <pre>
     *总页数
     * </pre>
     *
     * <code>int32 totalPage = 4;</code>
     */
    public int getTotalPage() {
      return totalPage_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pageSize_ != 0) {
        output.writeInt32(1, pageSize_);
      }
      if (currPage_ != 0) {
        output.writeInt32(2, currPage_);
      }
      if (totalCount_ != 0) {
        output.writeInt32(3, totalCount_);
      }
      if (totalPage_ != 0) {
        output.writeInt32(4, totalPage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pageSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pageSize_);
      }
      if (currPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, currPage_);
      }
      if (totalCount_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, totalCount_);
      }
      if (totalPage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, totalPage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.topsec.mobiapi.proto.BaseMessage.PageContent)) {
        return super.equals(obj);
      }
      com.topsec.mobiapi.proto.BaseMessage.PageContent other = (com.topsec.mobiapi.proto.BaseMessage.PageContent) obj;

      boolean result = true;
      result = result && (getPageSize()
          == other.getPageSize());
      result = result && (getCurrPage()
          == other.getCurrPage());
      result = result && (getTotalCount()
          == other.getTotalCount());
      result = result && (getTotalPage()
          == other.getTotalPage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PAGESIZE_FIELD_NUMBER;
      hash = (53 * hash) + getPageSize();
      hash = (37 * hash) + CURRPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getCurrPage();
      hash = (37 * hash) + TOTALCOUNT_FIELD_NUMBER;
      hash = (53 * hash) + getTotalCount();
      hash = (37 * hash) + TOTALPAGE_FIELD_NUMBER;
      hash = (53 * hash) + getTotalPage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.PageContent parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.topsec.mobiapi.proto.BaseMessage.PageContent prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     *分页查询条件
     * </pre>
     *
     * Protobuf type {@code com.topsec.mobiapi.proto.PageContent}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.topsec.mobiapi.proto.PageContent)
        com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_PageContent_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_PageContent_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.topsec.mobiapi.proto.BaseMessage.PageContent.class, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder.class);
      }

      // Construct using com.topsec.mobiapi.proto.BaseMessage.PageContent.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        pageSize_ = 0;

        currPage_ = 0;

        totalCount_ = 0;

        totalPage_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_PageContent_descriptor;
      }

      public com.topsec.mobiapi.proto.BaseMessage.PageContent getDefaultInstanceForType() {
        return com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance();
      }

      public com.topsec.mobiapi.proto.BaseMessage.PageContent build() {
        com.topsec.mobiapi.proto.BaseMessage.PageContent result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.topsec.mobiapi.proto.BaseMessage.PageContent buildPartial() {
        com.topsec.mobiapi.proto.BaseMessage.PageContent result = new com.topsec.mobiapi.proto.BaseMessage.PageContent(this);
        result.pageSize_ = pageSize_;
        result.currPage_ = currPage_;
        result.totalCount_ = totalCount_;
        result.totalPage_ = totalPage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.topsec.mobiapi.proto.BaseMessage.PageContent) {
          return mergeFrom((com.topsec.mobiapi.proto.BaseMessage.PageContent)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.topsec.mobiapi.proto.BaseMessage.PageContent other) {
        if (other == com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance()) return this;
        if (other.getPageSize() != 0) {
          setPageSize(other.getPageSize());
        }
        if (other.getCurrPage() != 0) {
          setCurrPage(other.getCurrPage());
        }
        if (other.getTotalCount() != 0) {
          setTotalCount(other.getTotalCount());
        }
        if (other.getTotalPage() != 0) {
          setTotalPage(other.getTotalPage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.topsec.mobiapi.proto.BaseMessage.PageContent parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.topsec.mobiapi.proto.BaseMessage.PageContent) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pageSize_ ;
      /**
       * <pre>
       *每页数据量大小
       * </pre>
       *
       * <code>int32 pageSize = 1;</code>
       */
      public int getPageSize() {
        return pageSize_;
      }
      /**
       * <pre>
       *每页数据量大小
       * </pre>
       *
       * <code>int32 pageSize = 1;</code>
       */
      public Builder setPageSize(int value) {
        
        pageSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *每页数据量大小
       * </pre>
       *
       * <code>int32 pageSize = 1;</code>
       */
      public Builder clearPageSize() {
        
        pageSize_ = 0;
        onChanged();
        return this;
      }

      private int currPage_ ;
      /**
       * <pre>
       *当前页码
       * </pre>
       *
       * <code>int32 currPage = 2;</code>
       */
      public int getCurrPage() {
        return currPage_;
      }
      /**
       * <pre>
       *当前页码
       * </pre>
       *
       * <code>int32 currPage = 2;</code>
       */
      public Builder setCurrPage(int value) {
        
        currPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *当前页码
       * </pre>
       *
       * <code>int32 currPage = 2;</code>
       */
      public Builder clearCurrPage() {
        
        currPage_ = 0;
        onChanged();
        return this;
      }

      private int totalCount_ ;
      /**
       * <pre>
       *总记录数
       * </pre>
       *
       * <code>int32 totalCount = 3;</code>
       */
      public int getTotalCount() {
        return totalCount_;
      }
      /**
       * <pre>
       *总记录数
       * </pre>
       *
       * <code>int32 totalCount = 3;</code>
       */
      public Builder setTotalCount(int value) {
        
        totalCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *总记录数
       * </pre>
       *
       * <code>int32 totalCount = 3;</code>
       */
      public Builder clearTotalCount() {
        
        totalCount_ = 0;
        onChanged();
        return this;
      }

      private int totalPage_ ;
      /**
       * <pre>
       *总页数
       * </pre>
       *
       * <code>int32 totalPage = 4;</code>
       */
      public int getTotalPage() {
        return totalPage_;
      }
      /**
       * <pre>
       *总页数
       * </pre>
       *
       * <code>int32 totalPage = 4;</code>
       */
      public Builder setTotalPage(int value) {
        
        totalPage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *总页数
       * </pre>
       *
       * <code>int32 totalPage = 4;</code>
       */
      public Builder clearTotalPage() {
        
        totalPage_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.topsec.mobiapi.proto.PageContent)
    }

    // @@protoc_insertion_point(class_scope:com.topsec.mobiapi.proto.PageContent)
    private static final com.topsec.mobiapi.proto.BaseMessage.PageContent DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.topsec.mobiapi.proto.BaseMessage.PageContent();
    }

    public static com.topsec.mobiapi.proto.BaseMessage.PageContent getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PageContent>
        PARSER = new com.google.protobuf.AbstractParser<PageContent>() {
      public PageContent parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PageContent(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PageContent> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PageContent> getParserForType() {
      return PARSER;
    }

    public com.topsec.mobiapi.proto.BaseMessage.PageContent getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BaseResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.topsec.mobiapi.proto.BaseResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *结果 0 成功，1 失败
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    int getResult();

    /**
     * <pre>
     *说明（成功）    “结果”
     * </pre>
     *
     * <code>string messsage = 2;</code>
     */
    java.lang.String getMesssage();
    /**
     * <pre>
     *说明（成功）    “结果”
     * </pre>
     *
     * <code>string messsage = 2;</code>
     */
    com.google.protobuf.ByteString
        getMesssageBytes();
  }
  /**
   * Protobuf type {@code com.topsec.mobiapi.proto.BaseResponse}
   */
  public  static final class BaseResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.topsec.mobiapi.proto.BaseResponse)
      BaseResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BaseResponse.newBuilder() to construct.
    private BaseResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BaseResponse() {
      result_ = 0;
      messsage_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BaseResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              result_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              messsage_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_BaseResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_BaseResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.topsec.mobiapi.proto.BaseMessage.BaseResponse.class, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private int result_;
    /**
     * <pre>
     *结果 0 成功，1 失败
     * </pre>
     *
     * <code>int32 result = 1;</code>
     */
    public int getResult() {
      return result_;
    }

    public static final int MESSSAGE_FIELD_NUMBER = 2;
    private volatile java.lang.Object messsage_;
    /**
     * <pre>
     *说明（成功）    “结果”
     * </pre>
     *
     * <code>string messsage = 2;</code>
     */
    public java.lang.String getMesssage() {
      java.lang.Object ref = messsage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        messsage_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *说明（成功）    “结果”
     * </pre>
     *
     * <code>string messsage = 2;</code>
     */
    public com.google.protobuf.ByteString
        getMesssageBytes() {
      java.lang.Object ref = messsage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        messsage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (result_ != 0) {
        output.writeInt32(1, result_);
      }
      if (!getMesssageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, messsage_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (result_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, result_);
      }
      if (!getMesssageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, messsage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.topsec.mobiapi.proto.BaseMessage.BaseResponse)) {
        return super.equals(obj);
      }
      com.topsec.mobiapi.proto.BaseMessage.BaseResponse other = (com.topsec.mobiapi.proto.BaseMessage.BaseResponse) obj;

      boolean result = true;
      result = result && (getResult()
          == other.getResult());
      result = result && getMesssage()
          .equals(other.getMesssage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult();
      hash = (37 * hash) + MESSSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMesssage().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.topsec.mobiapi.proto.BaseMessage.BaseResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.topsec.mobiapi.proto.BaseResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.topsec.mobiapi.proto.BaseResponse)
        com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_BaseResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_BaseResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.topsec.mobiapi.proto.BaseMessage.BaseResponse.class, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder.class);
      }

      // Construct using com.topsec.mobiapi.proto.BaseMessage.BaseResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        result_ = 0;

        messsage_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.topsec.mobiapi.proto.BaseMessage.internal_static_com_topsec_mobiapi_proto_BaseResponse_descriptor;
      }

      public com.topsec.mobiapi.proto.BaseMessage.BaseResponse getDefaultInstanceForType() {
        return com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance();
      }

      public com.topsec.mobiapi.proto.BaseMessage.BaseResponse build() {
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.topsec.mobiapi.proto.BaseMessage.BaseResponse buildPartial() {
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse result = new com.topsec.mobiapi.proto.BaseMessage.BaseResponse(this);
        result.result_ = result_;
        result.messsage_ = messsage_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.topsec.mobiapi.proto.BaseMessage.BaseResponse) {
          return mergeFrom((com.topsec.mobiapi.proto.BaseMessage.BaseResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.topsec.mobiapi.proto.BaseMessage.BaseResponse other) {
        if (other == com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance()) return this;
        if (other.getResult() != 0) {
          setResult(other.getResult());
        }
        if (!other.getMesssage().isEmpty()) {
          messsage_ = other.messsage_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.topsec.mobiapi.proto.BaseMessage.BaseResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int result_ ;
      /**
       * <pre>
       *结果 0 成功，1 失败
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public int getResult() {
        return result_;
      }
      /**
       * <pre>
       *结果 0 成功，1 失败
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder setResult(int value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *结果 0 成功，1 失败
       * </pre>
       *
       * <code>int32 result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object messsage_ = "";
      /**
       * <pre>
       *说明（成功）    “结果”
       * </pre>
       *
       * <code>string messsage = 2;</code>
       */
      public java.lang.String getMesssage() {
        java.lang.Object ref = messsage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          messsage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *说明（成功）    “结果”
       * </pre>
       *
       * <code>string messsage = 2;</code>
       */
      public com.google.protobuf.ByteString
          getMesssageBytes() {
        java.lang.Object ref = messsage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          messsage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *说明（成功）    “结果”
       * </pre>
       *
       * <code>string messsage = 2;</code>
       */
      public Builder setMesssage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        messsage_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *说明（成功）    “结果”
       * </pre>
       *
       * <code>string messsage = 2;</code>
       */
      public Builder clearMesssage() {
        
        messsage_ = getDefaultInstance().getMesssage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *说明（成功）    “结果”
       * </pre>
       *
       * <code>string messsage = 2;</code>
       */
      public Builder setMesssageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        messsage_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.topsec.mobiapi.proto.BaseResponse)
    }

    // @@protoc_insertion_point(class_scope:com.topsec.mobiapi.proto.BaseResponse)
    private static final com.topsec.mobiapi.proto.BaseMessage.BaseResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.topsec.mobiapi.proto.BaseMessage.BaseResponse();
    }

    public static com.topsec.mobiapi.proto.BaseMessage.BaseResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BaseResponse>
        PARSER = new com.google.protobuf.AbstractParser<BaseResponse>() {
      public BaseResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BaseResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BaseResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BaseResponse> getParserForType() {
      return PARSER;
    }

    public com.topsec.mobiapi.proto.BaseMessage.BaseResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_PageContent_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_PageContent_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_BaseResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_BaseResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021baseMessage.proto\022\030com.topsec.mobiapi." +
      "proto\"X\n\013PageContent\022\020\n\010pageSize\030\001 \001(\005\022\020" +
      "\n\010currPage\030\002 \001(\005\022\022\n\ntotalCount\030\003 \001(\005\022\021\n\t" +
      "totalPage\030\004 \001(\005\"0\n\014BaseResponse\022\016\n\006resul" +
      "t\030\001 \001(\005\022\020\n\010messsage\030\002 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_topsec_mobiapi_proto_PageContent_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_topsec_mobiapi_proto_PageContent_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_PageContent_descriptor,
        new java.lang.String[] { "PageSize", "CurrPage", "TotalCount", "TotalPage", });
    internal_static_com_topsec_mobiapi_proto_BaseResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_topsec_mobiapi_proto_BaseResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_BaseResponse_descriptor,
        new java.lang.String[] { "Result", "Messsage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
