// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.topsec.mobiapi.proto;

/**
 * <pre>
 * 渠道技术人员查询条件
 * </pre>
 *
 * Protobuf type {@code com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest}
 */
public  final class ChannelTechnicianInfoRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest)
    ChannelTechnicianInfoRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChannelTechnicianInfoRequest.newBuilder() to construct.
  private ChannelTechnicianInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChannelTechnicianInfoRequest() {
    searchCondition_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChannelTechnicianInfoRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            searchCondition_ = s;
            break;
          }
          case 18: {
            com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder subBuilder = null;
            if (pageContent_ != null) {
              subBuilder = pageContent_.toBuilder();
            }
            pageContent_ = input.readMessage(com.topsec.mobiapi.proto.BaseMessage.PageContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pageContent_);
              pageContent_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest.class, com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest.Builder.class);
  }

  public static final int SEARCHCONDITION_FIELD_NUMBER = 1;
  private volatile java.lang.Object searchCondition_;
  /**
   * <pre>
   *模糊查询条件
   * </pre>
   *
   * <code>string searchCondition = 1;</code>
   */
  public java.lang.String getSearchCondition() {
    java.lang.Object ref = searchCondition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      searchCondition_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *模糊查询条件
   * </pre>
   *
   * <code>string searchCondition = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSearchConditionBytes() {
    java.lang.Object ref = searchCondition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      searchCondition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PAGECONTENT_FIELD_NUMBER = 2;
  private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_;
  /**
   * <pre>
   *分页
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public boolean hasPageContent() {
    return pageContent_ != null;
  }
  /**
   * <pre>
   *分页
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
    return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
  }
  /**
   * <pre>
   *分页
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
    return getPageContent();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSearchConditionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, searchCondition_);
    }
    if (pageContent_ != null) {
      output.writeMessage(2, getPageContent());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSearchConditionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, searchCondition_);
    }
    if (pageContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPageContent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest)) {
      return super.equals(obj);
    }
    com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest other = (com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest) obj;

    boolean result = true;
    result = result && getSearchCondition()
        .equals(other.getSearchCondition());
    result = result && (hasPageContent() == other.hasPageContent());
    if (hasPageContent()) {
      result = result && getPageContent()
          .equals(other.getPageContent());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEARCHCONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getSearchCondition().hashCode();
    if (hasPageContent()) {
      hash = (37 * hash) + PAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getPageContent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 渠道技术人员查询条件
   * </pre>
   *
   * Protobuf type {@code com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest)
      com.topsec.mobiapi.proto.ChannelTechnicianInfoRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest.class, com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest.Builder.class);
    }

    // Construct using com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      searchCondition_ = "";

      if (pageContentBuilder_ == null) {
        pageContent_ = null;
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_descriptor;
    }

    public com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest getDefaultInstanceForType() {
      return com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest.getDefaultInstance();
    }

    public com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest build() {
      com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest buildPartial() {
      com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest result = new com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest(this);
      result.searchCondition_ = searchCondition_;
      if (pageContentBuilder_ == null) {
        result.pageContent_ = pageContent_;
      } else {
        result.pageContent_ = pageContentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest) {
        return mergeFrom((com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest other) {
      if (other == com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest.getDefaultInstance()) return this;
      if (!other.getSearchCondition().isEmpty()) {
        searchCondition_ = other.searchCondition_;
        onChanged();
      }
      if (other.hasPageContent()) {
        mergePageContent(other.getPageContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object searchCondition_ = "";
    /**
     * <pre>
     *模糊查询条件
     * </pre>
     *
     * <code>string searchCondition = 1;</code>
     */
    public java.lang.String getSearchCondition() {
      java.lang.Object ref = searchCondition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searchCondition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *模糊查询条件
     * </pre>
     *
     * <code>string searchCondition = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSearchConditionBytes() {
      java.lang.Object ref = searchCondition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchCondition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *模糊查询条件
     * </pre>
     *
     * <code>string searchCondition = 1;</code>
     */
    public Builder setSearchCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      searchCondition_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *模糊查询条件
     * </pre>
     *
     * <code>string searchCondition = 1;</code>
     */
    public Builder clearSearchCondition() {
      
      searchCondition_ = getDefaultInstance().getSearchCondition();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *模糊查询条件
     * </pre>
     *
     * <code>string searchCondition = 1;</code>
     */
    public Builder setSearchConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      searchCondition_ = value;
      onChanged();
      return this;
    }

    private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> pageContentBuilder_;
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public boolean hasPageContent() {
      return pageContentBuilder_ != null || pageContent_ != null;
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
      if (pageContentBuilder_ == null) {
        return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      } else {
        return pageContentBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder setPageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageContent_ = value;
        onChanged();
      } else {
        pageContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder setPageContent(
        com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder builderForValue) {
      if (pageContentBuilder_ == null) {
        pageContent_ = builderForValue.build();
        onChanged();
      } else {
        pageContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder mergePageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (pageContent_ != null) {
          pageContent_ =
            com.topsec.mobiapi.proto.BaseMessage.PageContent.newBuilder(pageContent_).mergeFrom(value).buildPartial();
        } else {
          pageContent_ = value;
        }
        onChanged();
      } else {
        pageContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder clearPageContent() {
      if (pageContentBuilder_ == null) {
        pageContent_ = null;
        onChanged();
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder getPageContentBuilder() {
      
      onChanged();
      return getPageContentFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
      if (pageContentBuilder_ != null) {
        return pageContentBuilder_.getMessageOrBuilder();
      } else {
        return pageContent_ == null ?
            com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      }
    }
    /**
     * <pre>
     *分页
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> 
        getPageContentFieldBuilder() {
      if (pageContentBuilder_ == null) {
        pageContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder>(
                getPageContent(),
                getParentForChildren(),
                isClean());
        pageContent_ = null;
      }
      return pageContentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest)
  }

  // @@protoc_insertion_point(class_scope:com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest)
  private static final com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest();
  }

  public static com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChannelTechnicianInfoRequest>
      PARSER = new com.google.protobuf.AbstractParser<ChannelTechnicianInfoRequest>() {
    public ChannelTechnicianInfoRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChannelTechnicianInfoRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChannelTechnicianInfoRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelTechnicianInfoRequest> getParserForType() {
    return PARSER;
  }

  public com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

