// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.topsec.mobiapi.proto;

public interface ChannelTechnicianInfoRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.topsec.mobiapi.proto.ChannelTechnicianInfoRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *模糊查询条件
   * </pre>
   *
   * <code>string searchCondition = 1;</code>
   */
  java.lang.String getSearchCondition();
  /**
   * <pre>
   *模糊查询条件
   * </pre>
   *
   * <code>string searchCondition = 1;</code>
   */
  com.google.protobuf.ByteString
      getSearchConditionBytes();

  /**
   * <pre>
   *分页
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  boolean hasPageContent();
  /**
   * <pre>
   *分页
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent();
  /**
   * <pre>
   *分页
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder();
}
