// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.topsec.mobiapi.proto;

public final class Channel {
  private Channel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_TechnicanCertificate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_TechnicanCertificate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rchannel.proto\022\030com.topsec.mobiapi.prot" +
      "o\032\021baseMessage.proto\"s\n\034ChannelTechnicia" +
      "nInfoRequest\022\027\n\017searchCondition\030\001 \001(\t\022:\n" +
      "\013pageContent\030\002 \001(\0132%.com.topsec.mobiapi." +
      "proto.PageContent\"\336\001\n!ChannelTechnicianI" +
      "nfoListResponse\022?\n\006ctInfo\030\001 \003(\0132/.com.to" +
      "psec.mobiapi.proto.ChannelTechnicianInfo" +
      "\022:\n\013pageContent\030\002 \001(\0132%.com.topsec.mobia" +
      "pi.proto.PageContent\022<\n\014BaseResponse\030\003 \001" +
      "(\0132&.com.topsec.mobiapi.proto.BaseRespon" +
      "se\"\330\001\n\036ChannelCompanyInfoListResponse\022<\n" +
      "\006ccInfo\030\001 \003(\0132,.com.topsec.mobiapi.proto" +
      ".ChannelCompanyInfo\022:\n\013pageContent\030\002 \001(\013" +
      "2%.com.topsec.mobiapi.proto.PageContent\022" +
      "<\n\014BaseResponse\030\003 \001(\0132&.com.topsec.mobia" +
      "pi.proto.BaseResponse\"\225\001\n\031ChannelCompany" +
      "InfoRequest\022\021\n\tstarLevel\030\001 \001(\005\022\020\n\010provin" +
      "ce\030\002 \001(\t\022\027\n\017searchCondition\030\003 \001(\t\022:\n\013pag" +
      "eContent\030\004 \001(\0132%.com.topsec.mobiapi.prot" +
      "o.PageContent\"\233\006\n\022ChannelCompanyInfo\022\013\n\003" +
      "cId\030\001 \001(\t\022\r\n\005cName\030\002 \001(\t\022\014\n\004addr\030\003 \001(\t\022\016" +
      "\n\006cEmail\030\004 \001(\t\022\022\n\npostalCode\030\005 \001(\t\022\013\n\003fa" +
      "x\030\006 \001(\t\022\021\n\ttelephone\030\007 \001(\t\022\020\n\010province\030\010" +
      " \001(\t\022\014\n\004city\030\t \001(\t\022\016\n\006county\030\n \001(\t\022\r\n\005cS" +
      "tar\030\013 \001(\005\022\022\n\nisSupplier\030\014 \001(\005\022\016\n\006cLevel\030" +
      "\r \001(\005\022\016\n\006cScale\030\016 \001(\005\022\016\n\006cScope\030\017 \001(\t\022\017\n" +
      "\007mainBus\030\020 \001(\t\022\014\n\004cUrl\030\021 \001(\t\022\020\n\010credCode" +
      "\030\022 \001(\t\022\031\n\021registeredCapital\030\023 \001(\001\022\026\n\016reg" +
      "isteredType\030\024 \001(\t\022\026\n\016registeredDate\030\025 \001(" +
      "\t\022\021\n\tlegalName\030\026 \001(\t\022\020\n\010legalSex\030\027 \001(\005\022\017" +
      "\n\007corpTax\030\030 \001(\t\022\r\n\005cBank\030\031 \001(\t\022\020\n\010cAccou" +
      "nt\030\032 \001(\t\022\023\n\013managerName\030\033 \001(\t\022\022\n\nmanager" +
      "Sex\030\034 \001(\005\022\024\n\014managerEmail\030\035 \001(\t\022\020\n\010techN" +
      "ame\030\036 \001(\t\022\017\n\007techSex\030\037 \001(\005\022\020\n\010techPost\030+" +
      " \001(\t\022\025\n\rtechTelephone\030  \001(\t\022\021\n\ttechPhone" +
      "\030! \001(\t\022\021\n\ttechEmail\030\" \001(\t\022\017\n\007busName\030# \001" +
      "(\t\022\016\n\006busSex\030$ \001(\005\022\017\n\007busPost\030% \001(\t\022\024\n\014b" +
      "usTelephone\030& \001(\t\022\020\n\010busPhone\030\' \001(\t\022\020\n\010b" +
      "usEmail\030( \001(\t\022\024\n\014notPassCause\030) \001(\t\022\016\n\006s" +
      "tatus\030* \001(\005\"\207\003\n\025ChannelTechnicianInfo\022\021\n" +
      "\tcompanyId\030\001 \001(\t\022\023\n\013companyName\030\002 \001(\t\022\022\n" +
      "\npersonName\030\003 \001(\t\022\024\n\014personGender\030\004 \001(\005\022" +
      "\013\n\003pId\030\005 \001(\t\022\016\n\006idCard\030\006 \001(\t\022\020\n\010birthday" +
      "\030\007 \001(\t\022\r\n\005phone\030\010 \001(\t\022\014\n\004prov\030\t \001(\t\022\014\n\004c" +
      "ity\030\n \001(\t\022\016\n\006county\030\013 \001(\t\022\017\n\007address\030\014 \001" +
      "(\t\022\013\n\003job\030\r \001(\t\022\r\n\005email\030\016 \001(\t\022\020\n\010hireDa" +
      "te\030\017 \001(\t\022\r\n\005qqNum\030\020 \001(\t\022\021\n\ttelephone\030\021 \001" +
      "(\t\022\021\n\treStatues\030\022 \001(\005\022>\n\006tcInfo\030\023 \003(\0132.." +
      "com.topsec.mobiapi.proto.TechnicanCertif" +
      "icate\"Q\n\024TechnicanCertificate\022\014\n\004tcId\030\001 " +
      "\001(\t\022\r\n\005tcDrt\030\002 \001(\t\022\014\n\004tcLv\030\003 \001(\t\022\016\n\006tcTi" +
      "me\030\004 \001(\t2\263\002\n\016ChannelService\022\223\001\n\032QueryAll" +
      "ChannelTechnicians\0226.com.topsec.mobiapi." +
      "proto.ChannelTechnicianInfoRequest\032;.com" +
      ".topsec.mobiapi.proto.ChannelTechnicianI" +
      "nfoListResponse\"\000\022\212\001\n\027QueryAllChannelCom" +
      "panys\0223.com.topsec.mobiapi.proto.Channel" +
      "CompanyInfoRequest\0328.com.topsec.mobiapi." +
      "proto.ChannelCompanyInfoListResponse\"\000B\034" +
      "\n\030com.topsec.mobiapi.protoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.topsec.mobiapi.proto.BaseMessage.getDescriptor(),
        }, assigner);
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoRequest_descriptor,
        new java.lang.String[] { "SearchCondition", "PageContent", });
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoListResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfoListResponse_descriptor,
        new java.lang.String[] { "CtInfo", "PageContent", "BaseResponse", });
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_descriptor,
        new java.lang.String[] { "CcInfo", "PageContent", "BaseResponse", });
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoRequest_descriptor,
        new java.lang.String[] { "StarLevel", "Province", "SearchCondition", "PageContent", });
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfo_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfo_descriptor,
        new java.lang.String[] { "CId", "CName", "Addr", "CEmail", "PostalCode", "Fax", "Telephone", "Province", "City", "County", "CStar", "IsSupplier", "CLevel", "CScale", "CScope", "MainBus", "CUrl", "CredCode", "RegisteredCapital", "RegisteredType", "RegisteredDate", "LegalName", "LegalSex", "CorpTax", "CBank", "CAccount", "ManagerName", "ManagerSex", "ManagerEmail", "TechName", "TechSex", "TechPost", "TechTelephone", "TechPhone", "TechEmail", "BusName", "BusSex", "BusPost", "BusTelephone", "BusPhone", "BusEmail", "NotPassCause", "Status", });
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfo_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_ChannelTechnicianInfo_descriptor,
        new java.lang.String[] { "CompanyId", "CompanyName", "PersonName", "PersonGender", "PId", "IdCard", "Birthday", "Phone", "Prov", "City", "County", "Address", "Job", "Email", "HireDate", "QqNum", "Telephone", "ReStatues", "TcInfo", });
    internal_static_com_topsec_mobiapi_proto_TechnicanCertificate_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_topsec_mobiapi_proto_TechnicanCertificate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_TechnicanCertificate_descriptor,
        new java.lang.String[] { "TcId", "TcDrt", "TcLv", "TcTime", });
    com.topsec.mobiapi.proto.BaseMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
