// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.topsec.mobiapi.proto;

public interface ChannelCompanyInfoListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  java.util.List<com.topsec.mobiapi.proto.ChannelCompanyInfo> 
      getCcInfoList();
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  com.topsec.mobiapi.proto.ChannelCompanyInfo getCcInfo(int index);
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  int getCcInfoCount();
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  java.util.List<? extends com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder> 
      getCcInfoOrBuilderList();
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder getCcInfoOrBuilder(
      int index);

  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  boolean hasPageContent();
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent();
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder();

  /**
   * <pre>
   *返回状态码+说明
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
   */
  boolean hasBaseResponse();
  /**
   * <pre>
   *返回状态码+说明
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.BaseResponse getBaseResponse();
  /**
   * <pre>
   *返回状态码+说明
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder getBaseResponseOrBuilder();
}
