// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.topsec.mobiapi.proto;

/**
 * Protobuf type {@code com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse}
 */
public  final class ChannelCompanyInfoListResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse)
    ChannelCompanyInfoListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ChannelCompanyInfoListResponse.newBuilder() to construct.
  private ChannelCompanyInfoListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ChannelCompanyInfoListResponse() {
    ccInfo_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ChannelCompanyInfoListResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              ccInfo_ = new java.util.ArrayList<com.topsec.mobiapi.proto.ChannelCompanyInfo>();
              mutable_bitField0_ |= 0x00000001;
            }
            ccInfo_.add(
                input.readMessage(com.topsec.mobiapi.proto.ChannelCompanyInfo.parser(), extensionRegistry));
            break;
          }
          case 18: {
            com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder subBuilder = null;
            if (pageContent_ != null) {
              subBuilder = pageContent_.toBuilder();
            }
            pageContent_ = input.readMessage(com.topsec.mobiapi.proto.BaseMessage.PageContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pageContent_);
              pageContent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder subBuilder = null;
            if (baseResponse_ != null) {
              subBuilder = baseResponse_.toBuilder();
            }
            baseResponse_ = input.readMessage(com.topsec.mobiapi.proto.BaseMessage.BaseResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResponse_);
              baseResponse_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        ccInfo_ = java.util.Collections.unmodifiableList(ccInfo_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse.class, com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse.Builder.class);
  }

  private int bitField0_;
  public static final int CCINFO_FIELD_NUMBER = 1;
  private java.util.List<com.topsec.mobiapi.proto.ChannelCompanyInfo> ccInfo_;
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  public java.util.List<com.topsec.mobiapi.proto.ChannelCompanyInfo> getCcInfoList() {
    return ccInfo_;
  }
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  public java.util.List<? extends com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder> 
      getCcInfoOrBuilderList() {
    return ccInfo_;
  }
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  public int getCcInfoCount() {
    return ccInfo_.size();
  }
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  public com.topsec.mobiapi.proto.ChannelCompanyInfo getCcInfo(int index) {
    return ccInfo_.get(index);
  }
  /**
   * <pre>
   *渠道商信息
   * </pre>
   *
   * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
   */
  public com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder getCcInfoOrBuilder(
      int index) {
    return ccInfo_.get(index);
  }

  public static final int PAGECONTENT_FIELD_NUMBER = 2;
  private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_;
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public boolean hasPageContent() {
    return pageContent_ != null;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
    return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
    return getPageContent();
  }

  public static final int BASERESPONSE_FIELD_NUMBER = 3;
  private com.topsec.mobiapi.proto.BaseMessage.BaseResponse baseResponse_;
  /**
   * <pre>
   *返回状态码+说明
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
   */
  public boolean hasBaseResponse() {
    return baseResponse_ != null;
  }
  /**
   * <pre>
   *返回状态码+说明
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <pre>
   *返回状态码+说明
   * </pre>
   *
   * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return getBaseResponse();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ccInfo_.size(); i++) {
      output.writeMessage(1, ccInfo_.get(i));
    }
    if (pageContent_ != null) {
      output.writeMessage(2, getPageContent());
    }
    if (baseResponse_ != null) {
      output.writeMessage(3, getBaseResponse());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < ccInfo_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, ccInfo_.get(i));
    }
    if (pageContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPageContent());
    }
    if (baseResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getBaseResponse());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse)) {
      return super.equals(obj);
    }
    com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse other = (com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse) obj;

    boolean result = true;
    result = result && getCcInfoList()
        .equals(other.getCcInfoList());
    result = result && (hasPageContent() == other.hasPageContent());
    if (hasPageContent()) {
      result = result && getPageContent()
          .equals(other.getPageContent());
    }
    result = result && (hasBaseResponse() == other.hasBaseResponse());
    if (hasBaseResponse()) {
      result = result && getBaseResponse()
          .equals(other.getBaseResponse());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getCcInfoCount() > 0) {
      hash = (37 * hash) + CCINFO_FIELD_NUMBER;
      hash = (53 * hash) + getCcInfoList().hashCode();
    }
    if (hasPageContent()) {
      hash = (37 * hash) + PAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getPageContent().hashCode();
    }
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse)
      com.topsec.mobiapi.proto.ChannelCompanyInfoListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse.class, com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse.Builder.class);
    }

    // Construct using com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getCcInfoFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (ccInfoBuilder_ == null) {
        ccInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        ccInfoBuilder_.clear();
      }
      if (pageContentBuilder_ == null) {
        pageContent_ = null;
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }
      if (baseResponseBuilder_ == null) {
        baseResponse_ = null;
      } else {
        baseResponse_ = null;
        baseResponseBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.topsec.mobiapi.proto.Channel.internal_static_com_topsec_mobiapi_proto_ChannelCompanyInfoListResponse_descriptor;
    }

    public com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse getDefaultInstanceForType() {
      return com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse.getDefaultInstance();
    }

    public com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse build() {
      com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse buildPartial() {
      com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse result = new com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (ccInfoBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          ccInfo_ = java.util.Collections.unmodifiableList(ccInfo_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.ccInfo_ = ccInfo_;
      } else {
        result.ccInfo_ = ccInfoBuilder_.build();
      }
      if (pageContentBuilder_ == null) {
        result.pageContent_ = pageContent_;
      } else {
        result.pageContent_ = pageContentBuilder_.build();
      }
      if (baseResponseBuilder_ == null) {
        result.baseResponse_ = baseResponse_;
      } else {
        result.baseResponse_ = baseResponseBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse) {
        return mergeFrom((com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse other) {
      if (other == com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse.getDefaultInstance()) return this;
      if (ccInfoBuilder_ == null) {
        if (!other.ccInfo_.isEmpty()) {
          if (ccInfo_.isEmpty()) {
            ccInfo_ = other.ccInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureCcInfoIsMutable();
            ccInfo_.addAll(other.ccInfo_);
          }
          onChanged();
        }
      } else {
        if (!other.ccInfo_.isEmpty()) {
          if (ccInfoBuilder_.isEmpty()) {
            ccInfoBuilder_.dispose();
            ccInfoBuilder_ = null;
            ccInfo_ = other.ccInfo_;
            bitField0_ = (bitField0_ & ~0x00000001);
            ccInfoBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getCcInfoFieldBuilder() : null;
          } else {
            ccInfoBuilder_.addAllMessages(other.ccInfo_);
          }
        }
      }
      if (other.hasPageContent()) {
        mergePageContent(other.getPageContent());
      }
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.topsec.mobiapi.proto.ChannelCompanyInfo> ccInfo_ =
      java.util.Collections.emptyList();
    private void ensureCcInfoIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        ccInfo_ = new java.util.ArrayList<com.topsec.mobiapi.proto.ChannelCompanyInfo>(ccInfo_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.topsec.mobiapi.proto.ChannelCompanyInfo, com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder, com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder> ccInfoBuilder_;

    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public java.util.List<com.topsec.mobiapi.proto.ChannelCompanyInfo> getCcInfoList() {
      if (ccInfoBuilder_ == null) {
        return java.util.Collections.unmodifiableList(ccInfo_);
      } else {
        return ccInfoBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public int getCcInfoCount() {
      if (ccInfoBuilder_ == null) {
        return ccInfo_.size();
      } else {
        return ccInfoBuilder_.getCount();
      }
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public com.topsec.mobiapi.proto.ChannelCompanyInfo getCcInfo(int index) {
      if (ccInfoBuilder_ == null) {
        return ccInfo_.get(index);
      } else {
        return ccInfoBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder setCcInfo(
        int index, com.topsec.mobiapi.proto.ChannelCompanyInfo value) {
      if (ccInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCcInfoIsMutable();
        ccInfo_.set(index, value);
        onChanged();
      } else {
        ccInfoBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder setCcInfo(
        int index, com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder builderForValue) {
      if (ccInfoBuilder_ == null) {
        ensureCcInfoIsMutable();
        ccInfo_.set(index, builderForValue.build());
        onChanged();
      } else {
        ccInfoBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder addCcInfo(com.topsec.mobiapi.proto.ChannelCompanyInfo value) {
      if (ccInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCcInfoIsMutable();
        ccInfo_.add(value);
        onChanged();
      } else {
        ccInfoBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder addCcInfo(
        int index, com.topsec.mobiapi.proto.ChannelCompanyInfo value) {
      if (ccInfoBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureCcInfoIsMutable();
        ccInfo_.add(index, value);
        onChanged();
      } else {
        ccInfoBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder addCcInfo(
        com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder builderForValue) {
      if (ccInfoBuilder_ == null) {
        ensureCcInfoIsMutable();
        ccInfo_.add(builderForValue.build());
        onChanged();
      } else {
        ccInfoBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder addCcInfo(
        int index, com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder builderForValue) {
      if (ccInfoBuilder_ == null) {
        ensureCcInfoIsMutable();
        ccInfo_.add(index, builderForValue.build());
        onChanged();
      } else {
        ccInfoBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder addAllCcInfo(
        java.lang.Iterable<? extends com.topsec.mobiapi.proto.ChannelCompanyInfo> values) {
      if (ccInfoBuilder_ == null) {
        ensureCcInfoIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, ccInfo_);
        onChanged();
      } else {
        ccInfoBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder clearCcInfo() {
      if (ccInfoBuilder_ == null) {
        ccInfo_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        ccInfoBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public Builder removeCcInfo(int index) {
      if (ccInfoBuilder_ == null) {
        ensureCcInfoIsMutable();
        ccInfo_.remove(index);
        onChanged();
      } else {
        ccInfoBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder getCcInfoBuilder(
        int index) {
      return getCcInfoFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder getCcInfoOrBuilder(
        int index) {
      if (ccInfoBuilder_ == null) {
        return ccInfo_.get(index);  } else {
        return ccInfoBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public java.util.List<? extends com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder> 
         getCcInfoOrBuilderList() {
      if (ccInfoBuilder_ != null) {
        return ccInfoBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(ccInfo_);
      }
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder addCcInfoBuilder() {
      return getCcInfoFieldBuilder().addBuilder(
          com.topsec.mobiapi.proto.ChannelCompanyInfo.getDefaultInstance());
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder addCcInfoBuilder(
        int index) {
      return getCcInfoFieldBuilder().addBuilder(
          index, com.topsec.mobiapi.proto.ChannelCompanyInfo.getDefaultInstance());
    }
    /**
     * <pre>
     *渠道商信息
     * </pre>
     *
     * <code>repeated .com.topsec.mobiapi.proto.ChannelCompanyInfo ccInfo = 1;</code>
     */
    public java.util.List<com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder> 
         getCcInfoBuilderList() {
      return getCcInfoFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.topsec.mobiapi.proto.ChannelCompanyInfo, com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder, com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder> 
        getCcInfoFieldBuilder() {
      if (ccInfoBuilder_ == null) {
        ccInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.topsec.mobiapi.proto.ChannelCompanyInfo, com.topsec.mobiapi.proto.ChannelCompanyInfo.Builder, com.topsec.mobiapi.proto.ChannelCompanyInfoOrBuilder>(
                ccInfo_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        ccInfo_ = null;
      }
      return ccInfoBuilder_;
    }

    private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> pageContentBuilder_;
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public boolean hasPageContent() {
      return pageContentBuilder_ != null || pageContent_ != null;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
      if (pageContentBuilder_ == null) {
        return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      } else {
        return pageContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder setPageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageContent_ = value;
        onChanged();
      } else {
        pageContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder setPageContent(
        com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder builderForValue) {
      if (pageContentBuilder_ == null) {
        pageContent_ = builderForValue.build();
        onChanged();
      } else {
        pageContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder mergePageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (pageContent_ != null) {
          pageContent_ =
            com.topsec.mobiapi.proto.BaseMessage.PageContent.newBuilder(pageContent_).mergeFrom(value).buildPartial();
        } else {
          pageContent_ = value;
        }
        onChanged();
      } else {
        pageContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder clearPageContent() {
      if (pageContentBuilder_ == null) {
        pageContent_ = null;
        onChanged();
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder getPageContentBuilder() {
      
      onChanged();
      return getPageContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
      if (pageContentBuilder_ != null) {
        return pageContentBuilder_.getMessageOrBuilder();
      } else {
        return pageContent_ == null ?
            com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> 
        getPageContentFieldBuilder() {
      if (pageContentBuilder_ == null) {
        pageContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder>(
                getPageContent(),
                getParentForChildren(),
                isClean());
        pageContent_ = null;
      }
      return pageContentBuilder_;
    }

    private com.topsec.mobiapi.proto.BaseMessage.BaseResponse baseResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder, com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public boolean hasBaseResponse() {
      return baseResponseBuilder_ != null || baseResponse_ != null;
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public Builder setBaseResponse(com.topsec.mobiapi.proto.BaseMessage.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
        onChanged();
      } else {
        baseResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public Builder setBaseResponse(
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
        onChanged();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public Builder mergeBaseResponse(com.topsec.mobiapi.proto.BaseMessage.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (baseResponse_ != null) {
          baseResponse_ =
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse.newBuilder(baseResponse_).mergeFrom(value).buildPartial();
        } else {
          baseResponse_ = value;
        }
        onChanged();
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public Builder clearBaseResponse() {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = null;
        onChanged();
      } else {
        baseResponse_ = null;
        baseResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder getBaseResponseBuilder() {
      
      onChanged();
      return getBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <pre>
     *返回状态码+说明
     * </pre>
     *
     * <code>.com.topsec.mobiapi.proto.BaseResponse BaseResponse = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder, com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder> 
        getBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder, com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse)
  }

  // @@protoc_insertion_point(class_scope:com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse)
  private static final com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse();
  }

  public static com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ChannelCompanyInfoListResponse>
      PARSER = new com.google.protobuf.AbstractParser<ChannelCompanyInfoListResponse>() {
    public ChannelCompanyInfoListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ChannelCompanyInfoListResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ChannelCompanyInfoListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ChannelCompanyInfoListResponse> getParserForType() {
    return PARSER;
  }

  public com.topsec.mobiapi.proto.ChannelCompanyInfoListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

