// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileManage.proto

package com.topsec.mobiapi.proto;

public final class FileManage {
  private FileManage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_FileQueryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_FileQueryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_topsec_mobiapi_proto_FileInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_topsec_mobiapi_proto_FileInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020fileManage.proto\022\030com.topsec.mobiapi.p" +
      "roto\032\021baseMessage.proto\"\317\001\n\020FileQueryReq" +
      "uest\022\027\n\017searchCondition\030\001 \001(\t\022?\n\005times\030\002" +
      " \001(\01620.com.topsec.mobiapi.proto.FileQuer" +
      "yRequest.Times\022:\n\013pageContent\030\003 \001(\0132%.co" +
      "m.topsec.mobiapi.proto.PageContent\"%\n\005Ti" +
      "mes\022\007\n\003DAY\020\000\022\010\n\004WEEK\020\001\022\t\n\005MONTH\020\002\"\305\001\n\023Ge" +
      "tFileInfoResponse\022<\n\014baseResponse\030\001 \001(\0132" +
      "&.com.topsec.mobiapi.proto.BaseResponse\022" +
      ":\n\013pageContent\030\002 \001(\0132%.com.topsec.mobiap" +
      "i.proto.PageContent\0224\n\010fileList\030\003 \003(\0132\"." +
      "com.topsec.mobiapi.proto.FileInfo\"\221\002\n\010Fi" +
      "leInfo\022\013\n\003fid\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004siz" +
      "e\030\003 \001(\t\022\020\n\010category\030\004 \001(\t\022\014\n\004type\030\005 \001(\t\022" +
      "\020\n\010watchUrl\030\006 \001(\t\022\023\n\013shareNumber\030\007 \001(\005\022\026" +
      "\n\016downloadNumber\030\010 \001(\005\022\021\n\tcreatedId\030\t \001(" +
      "\t\022\023\n\013createdName\030\n \001(\t\022\r\n\005ctime\030\013 \001(\t\022\021\n" +
      "\tupdatedId\030\014 \001(\t\022\023\n\013updatedName\030\r \001(\t\022\r\n" +
      "\005utime\030\016 \001(\t\022\017\n\007version\030\017 \001(\t2v\n\nFsmServ" +
      "ice\022h\n\013getFileList\022*.com.topsec.mobiapi." +
      "proto.FileQueryRequest\032-.com.topsec.mobi" +
      "api.proto.GetFileInfoResponseB\002P\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.topsec.mobiapi.proto.BaseMessage.getDescriptor(),
        }, assigner);
    internal_static_com_topsec_mobiapi_proto_FileQueryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_topsec_mobiapi_proto_FileQueryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_FileQueryRequest_descriptor,
        new java.lang.String[] { "SearchCondition", "Times", "PageContent", });
    internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_descriptor,
        new java.lang.String[] { "BaseResponse", "PageContent", "FileList", });
    internal_static_com_topsec_mobiapi_proto_FileInfo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_topsec_mobiapi_proto_FileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_topsec_mobiapi_proto_FileInfo_descriptor,
        new java.lang.String[] { "Fid", "Name", "Size", "Category", "Type", "WatchUrl", "ShareNumber", "DownloadNumber", "CreatedId", "CreatedName", "Ctime", "UpdatedId", "UpdatedName", "Utime", "Version", });
    com.topsec.mobiapi.proto.BaseMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
