// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileManage.proto

package com.topsec.mobiapi.proto;

/**
 * Protobuf type {@code com.topsec.mobiapi.proto.FileQueryRequest}
 */
public  final class FileQueryRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.topsec.mobiapi.proto.FileQueryRequest)
    FileQueryRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileQueryRequest.newBuilder() to construct.
  private FileQueryRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileQueryRequest() {
    searchCondition_ = "";
    times_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileQueryRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            searchCondition_ = s;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            times_ = rawValue;
            break;
          }
          case 26: {
            com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder subBuilder = null;
            if (pageContent_ != null) {
              subBuilder = pageContent_.toBuilder();
            }
            pageContent_ = input.readMessage(com.topsec.mobiapi.proto.BaseMessage.PageContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pageContent_);
              pageContent_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileQueryRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileQueryRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.topsec.mobiapi.proto.FileQueryRequest.class, com.topsec.mobiapi.proto.FileQueryRequest.Builder.class);
  }

  /**
   * <pre>
   *时间
   * </pre>
   *
   * Protobuf enum {@code com.topsec.mobiapi.proto.FileQueryRequest.Times}
   */
  public enum Times
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     *1天内
     * </pre>
     *
     * <code>DAY = 0;</code>
     */
    DAY(0),
    /**
     * <pre>
     *一周内
     * </pre>
     *
     * <code>WEEK = 1;</code>
     */
    WEEK(1),
    /**
     * <pre>
     *一个月内
     * </pre>
     *
     * <code>MONTH = 2;</code>
     */
    MONTH(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     *1天内
     * </pre>
     *
     * <code>DAY = 0;</code>
     */
    public static final int DAY_VALUE = 0;
    /**
     * <pre>
     *一周内
     * </pre>
     *
     * <code>WEEK = 1;</code>
     */
    public static final int WEEK_VALUE = 1;
    /**
     * <pre>
     *一个月内
     * </pre>
     *
     * <code>MONTH = 2;</code>
     */
    public static final int MONTH_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Times valueOf(int value) {
      return forNumber(value);
    }

    public static Times forNumber(int value) {
      switch (value) {
        case 0: return DAY;
        case 1: return WEEK;
        case 2: return MONTH;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Times>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Times> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Times>() {
            public Times findValueByNumber(int number) {
              return Times.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.FileQueryRequest.getDescriptor().getEnumTypes().get(0);
    }

    private static final Times[] VALUES = values();

    public static Times valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Times(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.topsec.mobiapi.proto.FileQueryRequest.Times)
  }

  public static final int SEARCHCONDITION_FIELD_NUMBER = 1;
  private volatile java.lang.Object searchCondition_;
  /**
   * <code>string searchCondition = 1;</code>
   */
  public java.lang.String getSearchCondition() {
    java.lang.Object ref = searchCondition_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      searchCondition_ = s;
      return s;
    }
  }
  /**
   * <code>string searchCondition = 1;</code>
   */
  public com.google.protobuf.ByteString
      getSearchConditionBytes() {
    java.lang.Object ref = searchCondition_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      searchCondition_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMES_FIELD_NUMBER = 2;
  private int times_;
  /**
   * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
   */
  public int getTimesValue() {
    return times_;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
   */
  public com.topsec.mobiapi.proto.FileQueryRequest.Times getTimes() {
    com.topsec.mobiapi.proto.FileQueryRequest.Times result = com.topsec.mobiapi.proto.FileQueryRequest.Times.valueOf(times_);
    return result == null ? com.topsec.mobiapi.proto.FileQueryRequest.Times.UNRECOGNIZED : result;
  }

  public static final int PAGECONTENT_FIELD_NUMBER = 3;
  private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_;
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
   */
  public boolean hasPageContent() {
    return pageContent_ != null;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
    return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
    return getPageContent();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getSearchConditionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, searchCondition_);
    }
    if (times_ != com.topsec.mobiapi.proto.FileQueryRequest.Times.DAY.getNumber()) {
      output.writeEnum(2, times_);
    }
    if (pageContent_ != null) {
      output.writeMessage(3, getPageContent());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getSearchConditionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, searchCondition_);
    }
    if (times_ != com.topsec.mobiapi.proto.FileQueryRequest.Times.DAY.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, times_);
    }
    if (pageContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, getPageContent());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.topsec.mobiapi.proto.FileQueryRequest)) {
      return super.equals(obj);
    }
    com.topsec.mobiapi.proto.FileQueryRequest other = (com.topsec.mobiapi.proto.FileQueryRequest) obj;

    boolean result = true;
    result = result && getSearchCondition()
        .equals(other.getSearchCondition());
    result = result && times_ == other.times_;
    result = result && (hasPageContent() == other.hasPageContent());
    if (hasPageContent()) {
      result = result && getPageContent()
          .equals(other.getPageContent());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SEARCHCONDITION_FIELD_NUMBER;
    hash = (53 * hash) + getSearchCondition().hashCode();
    hash = (37 * hash) + TIMES_FIELD_NUMBER;
    hash = (53 * hash) + times_;
    if (hasPageContent()) {
      hash = (37 * hash) + PAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getPageContent().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.FileQueryRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.topsec.mobiapi.proto.FileQueryRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.topsec.mobiapi.proto.FileQueryRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.topsec.mobiapi.proto.FileQueryRequest)
      com.topsec.mobiapi.proto.FileQueryRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileQueryRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileQueryRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.topsec.mobiapi.proto.FileQueryRequest.class, com.topsec.mobiapi.proto.FileQueryRequest.Builder.class);
    }

    // Construct using com.topsec.mobiapi.proto.FileQueryRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      searchCondition_ = "";

      times_ = 0;

      if (pageContentBuilder_ == null) {
        pageContent_ = null;
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileQueryRequest_descriptor;
    }

    public com.topsec.mobiapi.proto.FileQueryRequest getDefaultInstanceForType() {
      return com.topsec.mobiapi.proto.FileQueryRequest.getDefaultInstance();
    }

    public com.topsec.mobiapi.proto.FileQueryRequest build() {
      com.topsec.mobiapi.proto.FileQueryRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.topsec.mobiapi.proto.FileQueryRequest buildPartial() {
      com.topsec.mobiapi.proto.FileQueryRequest result = new com.topsec.mobiapi.proto.FileQueryRequest(this);
      result.searchCondition_ = searchCondition_;
      result.times_ = times_;
      if (pageContentBuilder_ == null) {
        result.pageContent_ = pageContent_;
      } else {
        result.pageContent_ = pageContentBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.topsec.mobiapi.proto.FileQueryRequest) {
        return mergeFrom((com.topsec.mobiapi.proto.FileQueryRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.topsec.mobiapi.proto.FileQueryRequest other) {
      if (other == com.topsec.mobiapi.proto.FileQueryRequest.getDefaultInstance()) return this;
      if (!other.getSearchCondition().isEmpty()) {
        searchCondition_ = other.searchCondition_;
        onChanged();
      }
      if (other.times_ != 0) {
        setTimesValue(other.getTimesValue());
      }
      if (other.hasPageContent()) {
        mergePageContent(other.getPageContent());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.topsec.mobiapi.proto.FileQueryRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.topsec.mobiapi.proto.FileQueryRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object searchCondition_ = "";
    /**
     * <code>string searchCondition = 1;</code>
     */
    public java.lang.String getSearchCondition() {
      java.lang.Object ref = searchCondition_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searchCondition_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string searchCondition = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSearchConditionBytes() {
      java.lang.Object ref = searchCondition_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchCondition_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string searchCondition = 1;</code>
     */
    public Builder setSearchCondition(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      searchCondition_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string searchCondition = 1;</code>
     */
    public Builder clearSearchCondition() {
      
      searchCondition_ = getDefaultInstance().getSearchCondition();
      onChanged();
      return this;
    }
    /**
     * <code>string searchCondition = 1;</code>
     */
    public Builder setSearchConditionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      searchCondition_ = value;
      onChanged();
      return this;
    }

    private int times_ = 0;
    /**
     * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
     */
    public int getTimesValue() {
      return times_;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
     */
    public Builder setTimesValue(int value) {
      times_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
     */
    public com.topsec.mobiapi.proto.FileQueryRequest.Times getTimes() {
      com.topsec.mobiapi.proto.FileQueryRequest.Times result = com.topsec.mobiapi.proto.FileQueryRequest.Times.valueOf(times_);
      return result == null ? com.topsec.mobiapi.proto.FileQueryRequest.Times.UNRECOGNIZED : result;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
     */
    public Builder setTimes(com.topsec.mobiapi.proto.FileQueryRequest.Times value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      times_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
     */
    public Builder clearTimes() {
      
      times_ = 0;
      onChanged();
      return this;
    }

    private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> pageContentBuilder_;
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public boolean hasPageContent() {
      return pageContentBuilder_ != null || pageContent_ != null;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
      if (pageContentBuilder_ == null) {
        return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      } else {
        return pageContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public Builder setPageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageContent_ = value;
        onChanged();
      } else {
        pageContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public Builder setPageContent(
        com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder builderForValue) {
      if (pageContentBuilder_ == null) {
        pageContent_ = builderForValue.build();
        onChanged();
      } else {
        pageContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public Builder mergePageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (pageContent_ != null) {
          pageContent_ =
            com.topsec.mobiapi.proto.BaseMessage.PageContent.newBuilder(pageContent_).mergeFrom(value).buildPartial();
        } else {
          pageContent_ = value;
        }
        onChanged();
      } else {
        pageContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public Builder clearPageContent() {
      if (pageContentBuilder_ == null) {
        pageContent_ = null;
        onChanged();
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder getPageContentBuilder() {
      
      onChanged();
      return getPageContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
      if (pageContentBuilder_ != null) {
        return pageContentBuilder_.getMessageOrBuilder();
      } else {
        return pageContent_ == null ?
            com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> 
        getPageContentFieldBuilder() {
      if (pageContentBuilder_ == null) {
        pageContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder>(
                getPageContent(),
                getParentForChildren(),
                isClean());
        pageContent_ = null;
      }
      return pageContentBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.topsec.mobiapi.proto.FileQueryRequest)
  }

  // @@protoc_insertion_point(class_scope:com.topsec.mobiapi.proto.FileQueryRequest)
  private static final com.topsec.mobiapi.proto.FileQueryRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.topsec.mobiapi.proto.FileQueryRequest();
  }

  public static com.topsec.mobiapi.proto.FileQueryRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileQueryRequest>
      PARSER = new com.google.protobuf.AbstractParser<FileQueryRequest>() {
    public FileQueryRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileQueryRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileQueryRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileQueryRequest> getParserForType() {
    return PARSER;
  }

  public com.topsec.mobiapi.proto.FileQueryRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

