// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileManage.proto

package com.topsec.mobiapi.proto;

/**
 * <pre>
 *文件信息
 * </pre>
 *
 * Protobuf type {@code com.topsec.mobiapi.proto.FileInfo}
 */
public  final class FileInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.topsec.mobiapi.proto.FileInfo)
    FileInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FileInfo.newBuilder() to construct.
  private FileInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FileInfo() {
    fid_ = "";
    name_ = "";
    size_ = "";
    category_ = "";
    type_ = "";
    watchUrl_ = "";
    shareNumber_ = 0;
    downloadNumber_ = 0;
    createdId_ = "";
    createdName_ = "";
    ctime_ = "";
    updatedId_ = "";
    updatedName_ = "";
    utime_ = "";
    version_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FileInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            fid_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            size_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            category_ = s;
            break;
          }
          case 42: {
            java.lang.String s = input.readStringRequireUtf8();

            type_ = s;
            break;
          }
          case 50: {
            java.lang.String s = input.readStringRequireUtf8();

            watchUrl_ = s;
            break;
          }
          case 56: {

            shareNumber_ = input.readInt32();
            break;
          }
          case 64: {

            downloadNumber_ = input.readInt32();
            break;
          }
          case 74: {
            java.lang.String s = input.readStringRequireUtf8();

            createdId_ = s;
            break;
          }
          case 82: {
            java.lang.String s = input.readStringRequireUtf8();

            createdName_ = s;
            break;
          }
          case 90: {
            java.lang.String s = input.readStringRequireUtf8();

            ctime_ = s;
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            updatedId_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            updatedName_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            utime_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            version_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileInfo_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.topsec.mobiapi.proto.FileInfo.class, com.topsec.mobiapi.proto.FileInfo.Builder.class);
  }

  public static final int FID_FIELD_NUMBER = 1;
  private volatile java.lang.Object fid_;
  /**
   * <pre>
   *文件ID
   * </pre>
   *
   * <code>string fid = 1;</code>
   */
  public java.lang.String getFid() {
    java.lang.Object ref = fid_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fid_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件ID
   * </pre>
   *
   * <code>string fid = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFidBytes() {
    java.lang.Object ref = fid_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fid_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   *文件名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件名称
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private volatile java.lang.Object size_;
  /**
   * <pre>
   *文件大小
   * </pre>
   *
   * <code>string size = 3;</code>
   */
  public java.lang.String getSize() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      size_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件大小
   * </pre>
   *
   * <code>string size = 3;</code>
   */
  public com.google.protobuf.ByteString
      getSizeBytes() {
    java.lang.Object ref = size_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      size_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CATEGORY_FIELD_NUMBER = 4;
  private volatile java.lang.Object category_;
  /**
   * <pre>
   *文件类型
   * </pre>
   *
   * <code>string category = 4;</code>
   */
  public java.lang.String getCategory() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      category_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件类型
   * </pre>
   *
   * <code>string category = 4;</code>
   */
  public com.google.protobuf.ByteString
      getCategoryBytes() {
    java.lang.Object ref = category_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      category_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 5;
  private volatile java.lang.Object type_;
  /**
   * <pre>
   *文件分类
   * </pre>
   *
   * <code>string type = 5;</code>
   */
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件分类
   * </pre>
   *
   * <code>string type = 5;</code>
   */
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WATCHURL_FIELD_NUMBER = 6;
  private volatile java.lang.Object watchUrl_;
  /**
   * <pre>
   *文件预览路径
   * </pre>
   *
   * <code>string watchUrl = 6;</code>
   */
  public java.lang.String getWatchUrl() {
    java.lang.Object ref = watchUrl_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      watchUrl_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *文件预览路径
   * </pre>
   *
   * <code>string watchUrl = 6;</code>
   */
  public com.google.protobuf.ByteString
      getWatchUrlBytes() {
    java.lang.Object ref = watchUrl_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      watchUrl_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SHARENUMBER_FIELD_NUMBER = 7;
  private int shareNumber_;
  /**
   * <pre>
   *文件分享次数
   * </pre>
   *
   * <code>int32 shareNumber = 7;</code>
   */
  public int getShareNumber() {
    return shareNumber_;
  }

  public static final int DOWNLOADNUMBER_FIELD_NUMBER = 8;
  private int downloadNumber_;
  /**
   * <pre>
   *文件下载次数
   * </pre>
   *
   * <code>int32 downloadNumber = 8;</code>
   */
  public int getDownloadNumber() {
    return downloadNumber_;
  }

  public static final int CREATEDID_FIELD_NUMBER = 9;
  private volatile java.lang.Object createdId_;
  /**
   * <pre>
   *创建人ID
   * </pre>
   *
   * <code>string createdId = 9;</code>
   */
  public java.lang.String getCreatedId() {
    java.lang.Object ref = createdId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *创建人ID
   * </pre>
   *
   * <code>string createdId = 9;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedIdBytes() {
    java.lang.Object ref = createdId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATEDNAME_FIELD_NUMBER = 10;
  private volatile java.lang.Object createdName_;
  /**
   * <pre>
   *创建人姓名
   * </pre>
   *
   * <code>string createdName = 10;</code>
   */
  public java.lang.String getCreatedName() {
    java.lang.Object ref = createdName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      createdName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *创建人姓名
   * </pre>
   *
   * <code>string createdName = 10;</code>
   */
  public com.google.protobuf.ByteString
      getCreatedNameBytes() {
    java.lang.Object ref = createdName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      createdName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CTIME_FIELD_NUMBER = 11;
  private volatile java.lang.Object ctime_;
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string ctime = 11;</code>
   */
  public java.lang.String getCtime() {
    java.lang.Object ref = ctime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ctime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *创建时间
   * </pre>
   *
   * <code>string ctime = 11;</code>
   */
  public com.google.protobuf.ByteString
      getCtimeBytes() {
    java.lang.Object ref = ctime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ctime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATEDID_FIELD_NUMBER = 12;
  private volatile java.lang.Object updatedId_;
  /**
   * <pre>
   *更新人ID
   * </pre>
   *
   * <code>string updatedId = 12;</code>
   */
  public java.lang.String getUpdatedId() {
    java.lang.Object ref = updatedId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updatedId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *更新人ID
   * </pre>
   *
   * <code>string updatedId = 12;</code>
   */
  public com.google.protobuf.ByteString
      getUpdatedIdBytes() {
    java.lang.Object ref = updatedId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updatedId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATEDNAME_FIELD_NUMBER = 13;
  private volatile java.lang.Object updatedName_;
  /**
   * <pre>
   *更新人姓名
   * </pre>
   *
   * <code>string updatedName = 13;</code>
   */
  public java.lang.String getUpdatedName() {
    java.lang.Object ref = updatedName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      updatedName_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *更新人姓名
   * </pre>
   *
   * <code>string updatedName = 13;</code>
   */
  public com.google.protobuf.ByteString
      getUpdatedNameBytes() {
    java.lang.Object ref = updatedName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      updatedName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UTIME_FIELD_NUMBER = 14;
  private volatile java.lang.Object utime_;
  /**
   * <pre>
   *更新时间
   * </pre>
   *
   * <code>string utime = 14;</code>
   */
  public java.lang.String getUtime() {
    java.lang.Object ref = utime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      utime_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *更新时间
   * </pre>
   *
   * <code>string utime = 14;</code>
   */
  public com.google.protobuf.ByteString
      getUtimeBytes() {
    java.lang.Object ref = utime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      utime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int VERSION_FIELD_NUMBER = 15;
  private volatile java.lang.Object version_;
  /**
   * <pre>
   *版本
   * </pre>
   *
   * <code>string version = 15;</code>
   */
  public java.lang.String getVersion() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      version_ = s;
      return s;
    }
  }
  /**
   * <pre>
   *版本
   * </pre>
   *
   * <code>string version = 15;</code>
   */
  public com.google.protobuf.ByteString
      getVersionBytes() {
    java.lang.Object ref = version_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      version_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getFidBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, fid_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (!getSizeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, size_);
    }
    if (!getCategoryBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, category_);
    }
    if (!getTypeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 5, type_);
    }
    if (!getWatchUrlBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 6, watchUrl_);
    }
    if (shareNumber_ != 0) {
      output.writeInt32(7, shareNumber_);
    }
    if (downloadNumber_ != 0) {
      output.writeInt32(8, downloadNumber_);
    }
    if (!getCreatedIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 9, createdId_);
    }
    if (!getCreatedNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 10, createdName_);
    }
    if (!getCtimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 11, ctime_);
    }
    if (!getUpdatedIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, updatedId_);
    }
    if (!getUpdatedNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, updatedName_);
    }
    if (!getUtimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, utime_);
    }
    if (!getVersionBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, version_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getFidBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, fid_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (!getSizeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, size_);
    }
    if (!getCategoryBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, category_);
    }
    if (!getTypeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, type_);
    }
    if (!getWatchUrlBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, watchUrl_);
    }
    if (shareNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, shareNumber_);
    }
    if (downloadNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, downloadNumber_);
    }
    if (!getCreatedIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, createdId_);
    }
    if (!getCreatedNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, createdName_);
    }
    if (!getCtimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, ctime_);
    }
    if (!getUpdatedIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, updatedId_);
    }
    if (!getUpdatedNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, updatedName_);
    }
    if (!getUtimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, utime_);
    }
    if (!getVersionBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, version_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.topsec.mobiapi.proto.FileInfo)) {
      return super.equals(obj);
    }
    com.topsec.mobiapi.proto.FileInfo other = (com.topsec.mobiapi.proto.FileInfo) obj;

    boolean result = true;
    result = result && getFid()
        .equals(other.getFid());
    result = result && getName()
        .equals(other.getName());
    result = result && getSize()
        .equals(other.getSize());
    result = result && getCategory()
        .equals(other.getCategory());
    result = result && getType()
        .equals(other.getType());
    result = result && getWatchUrl()
        .equals(other.getWatchUrl());
    result = result && (getShareNumber()
        == other.getShareNumber());
    result = result && (getDownloadNumber()
        == other.getDownloadNumber());
    result = result && getCreatedId()
        .equals(other.getCreatedId());
    result = result && getCreatedName()
        .equals(other.getCreatedName());
    result = result && getCtime()
        .equals(other.getCtime());
    result = result && getUpdatedId()
        .equals(other.getUpdatedId());
    result = result && getUpdatedName()
        .equals(other.getUpdatedName());
    result = result && getUtime()
        .equals(other.getUtime());
    result = result && getVersion()
        .equals(other.getVersion());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + FID_FIELD_NUMBER;
    hash = (53 * hash) + getFid().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + SIZE_FIELD_NUMBER;
    hash = (53 * hash) + getSize().hashCode();
    hash = (37 * hash) + CATEGORY_FIELD_NUMBER;
    hash = (53 * hash) + getCategory().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + WATCHURL_FIELD_NUMBER;
    hash = (53 * hash) + getWatchUrl().hashCode();
    hash = (37 * hash) + SHARENUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getShareNumber();
    hash = (37 * hash) + DOWNLOADNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getDownloadNumber();
    hash = (37 * hash) + CREATEDID_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedId().hashCode();
    hash = (37 * hash) + CREATEDNAME_FIELD_NUMBER;
    hash = (53 * hash) + getCreatedName().hashCode();
    hash = (37 * hash) + CTIME_FIELD_NUMBER;
    hash = (53 * hash) + getCtime().hashCode();
    hash = (37 * hash) + UPDATEDID_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedId().hashCode();
    hash = (37 * hash) + UPDATEDNAME_FIELD_NUMBER;
    hash = (53 * hash) + getUpdatedName().hashCode();
    hash = (37 * hash) + UTIME_FIELD_NUMBER;
    hash = (53 * hash) + getUtime().hashCode();
    hash = (37 * hash) + VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getVersion().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.FileInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.topsec.mobiapi.proto.FileInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *文件信息
   * </pre>
   *
   * Protobuf type {@code com.topsec.mobiapi.proto.FileInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.topsec.mobiapi.proto.FileInfo)
      com.topsec.mobiapi.proto.FileInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.topsec.mobiapi.proto.FileInfo.class, com.topsec.mobiapi.proto.FileInfo.Builder.class);
    }

    // Construct using com.topsec.mobiapi.proto.FileInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      fid_ = "";

      name_ = "";

      size_ = "";

      category_ = "";

      type_ = "";

      watchUrl_ = "";

      shareNumber_ = 0;

      downloadNumber_ = 0;

      createdId_ = "";

      createdName_ = "";

      ctime_ = "";

      updatedId_ = "";

      updatedName_ = "";

      utime_ = "";

      version_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_FileInfo_descriptor;
    }

    public com.topsec.mobiapi.proto.FileInfo getDefaultInstanceForType() {
      return com.topsec.mobiapi.proto.FileInfo.getDefaultInstance();
    }

    public com.topsec.mobiapi.proto.FileInfo build() {
      com.topsec.mobiapi.proto.FileInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.topsec.mobiapi.proto.FileInfo buildPartial() {
      com.topsec.mobiapi.proto.FileInfo result = new com.topsec.mobiapi.proto.FileInfo(this);
      result.fid_ = fid_;
      result.name_ = name_;
      result.size_ = size_;
      result.category_ = category_;
      result.type_ = type_;
      result.watchUrl_ = watchUrl_;
      result.shareNumber_ = shareNumber_;
      result.downloadNumber_ = downloadNumber_;
      result.createdId_ = createdId_;
      result.createdName_ = createdName_;
      result.ctime_ = ctime_;
      result.updatedId_ = updatedId_;
      result.updatedName_ = updatedName_;
      result.utime_ = utime_;
      result.version_ = version_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.topsec.mobiapi.proto.FileInfo) {
        return mergeFrom((com.topsec.mobiapi.proto.FileInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.topsec.mobiapi.proto.FileInfo other) {
      if (other == com.topsec.mobiapi.proto.FileInfo.getDefaultInstance()) return this;
      if (!other.getFid().isEmpty()) {
        fid_ = other.fid_;
        onChanged();
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (!other.getSize().isEmpty()) {
        size_ = other.size_;
        onChanged();
      }
      if (!other.getCategory().isEmpty()) {
        category_ = other.category_;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        onChanged();
      }
      if (!other.getWatchUrl().isEmpty()) {
        watchUrl_ = other.watchUrl_;
        onChanged();
      }
      if (other.getShareNumber() != 0) {
        setShareNumber(other.getShareNumber());
      }
      if (other.getDownloadNumber() != 0) {
        setDownloadNumber(other.getDownloadNumber());
      }
      if (!other.getCreatedId().isEmpty()) {
        createdId_ = other.createdId_;
        onChanged();
      }
      if (!other.getCreatedName().isEmpty()) {
        createdName_ = other.createdName_;
        onChanged();
      }
      if (!other.getCtime().isEmpty()) {
        ctime_ = other.ctime_;
        onChanged();
      }
      if (!other.getUpdatedId().isEmpty()) {
        updatedId_ = other.updatedId_;
        onChanged();
      }
      if (!other.getUpdatedName().isEmpty()) {
        updatedName_ = other.updatedName_;
        onChanged();
      }
      if (!other.getUtime().isEmpty()) {
        utime_ = other.utime_;
        onChanged();
      }
      if (!other.getVersion().isEmpty()) {
        version_ = other.version_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.topsec.mobiapi.proto.FileInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.topsec.mobiapi.proto.FileInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object fid_ = "";
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string fid = 1;</code>
     */
    public java.lang.String getFid() {
      java.lang.Object ref = fid_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fid_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string fid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFidBytes() {
      java.lang.Object ref = fid_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string fid = 1;</code>
     */
    public Builder setFid(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fid_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string fid = 1;</code>
     */
    public Builder clearFid() {
      
      fid_ = getDefaultInstance().getFid();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件ID
     * </pre>
     *
     * <code>string fid = 1;</code>
     */
    public Builder setFidBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fid_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     *文件名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *文件名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件名称
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object size_ = "";
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>string size = 3;</code>
     */
    public java.lang.String getSize() {
      java.lang.Object ref = size_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        size_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>string size = 3;</code>
     */
    public com.google.protobuf.ByteString
        getSizeBytes() {
      java.lang.Object ref = size_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        size_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>string size = 3;</code>
     */
    public Builder setSize(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      size_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>string size = 3;</code>
     */
    public Builder clearSize() {
      
      size_ = getDefaultInstance().getSize();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件大小
     * </pre>
     *
     * <code>string size = 3;</code>
     */
    public Builder setSizeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      size_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object category_ = "";
    /**
     * <pre>
     *文件类型
     * </pre>
     *
     * <code>string category = 4;</code>
     */
    public java.lang.String getCategory() {
      java.lang.Object ref = category_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        category_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *文件类型
     * </pre>
     *
     * <code>string category = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCategoryBytes() {
      java.lang.Object ref = category_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        category_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件类型
     * </pre>
     *
     * <code>string category = 4;</code>
     */
    public Builder setCategory(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      category_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件类型
     * </pre>
     *
     * <code>string category = 4;</code>
     */
    public Builder clearCategory() {
      
      category_ = getDefaultInstance().getCategory();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件类型
     * </pre>
     *
     * <code>string category = 4;</code>
     */
    public Builder setCategoryBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      category_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     *文件分类
     * </pre>
     *
     * <code>string type = 5;</code>
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *文件分类
     * </pre>
     *
     * <code>string type = 5;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件分类
     * </pre>
     *
     * <code>string type = 5;</code>
     */
    public Builder setType(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件分类
     * </pre>
     *
     * <code>string type = 5;</code>
     */
    public Builder clearType() {
      
      type_ = getDefaultInstance().getType();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件分类
     * </pre>
     *
     * <code>string type = 5;</code>
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      type_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object watchUrl_ = "";
    /**
     * <pre>
     *文件预览路径
     * </pre>
     *
     * <code>string watchUrl = 6;</code>
     */
    public java.lang.String getWatchUrl() {
      java.lang.Object ref = watchUrl_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        watchUrl_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *文件预览路径
     * </pre>
     *
     * <code>string watchUrl = 6;</code>
     */
    public com.google.protobuf.ByteString
        getWatchUrlBytes() {
      java.lang.Object ref = watchUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        watchUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *文件预览路径
     * </pre>
     *
     * <code>string watchUrl = 6;</code>
     */
    public Builder setWatchUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      watchUrl_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件预览路径
     * </pre>
     *
     * <code>string watchUrl = 6;</code>
     */
    public Builder clearWatchUrl() {
      
      watchUrl_ = getDefaultInstance().getWatchUrl();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件预览路径
     * </pre>
     *
     * <code>string watchUrl = 6;</code>
     */
    public Builder setWatchUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      watchUrl_ = value;
      onChanged();
      return this;
    }

    private int shareNumber_ ;
    /**
     * <pre>
     *文件分享次数
     * </pre>
     *
     * <code>int32 shareNumber = 7;</code>
     */
    public int getShareNumber() {
      return shareNumber_;
    }
    /**
     * <pre>
     *文件分享次数
     * </pre>
     *
     * <code>int32 shareNumber = 7;</code>
     */
    public Builder setShareNumber(int value) {
      
      shareNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件分享次数
     * </pre>
     *
     * <code>int32 shareNumber = 7;</code>
     */
    public Builder clearShareNumber() {
      
      shareNumber_ = 0;
      onChanged();
      return this;
    }

    private int downloadNumber_ ;
    /**
     * <pre>
     *文件下载次数
     * </pre>
     *
     * <code>int32 downloadNumber = 8;</code>
     */
    public int getDownloadNumber() {
      return downloadNumber_;
    }
    /**
     * <pre>
     *文件下载次数
     * </pre>
     *
     * <code>int32 downloadNumber = 8;</code>
     */
    public Builder setDownloadNumber(int value) {
      
      downloadNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *文件下载次数
     * </pre>
     *
     * <code>int32 downloadNumber = 8;</code>
     */
    public Builder clearDownloadNumber() {
      
      downloadNumber_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object createdId_ = "";
    /**
     * <pre>
     *创建人ID
     * </pre>
     *
     * <code>string createdId = 9;</code>
     */
    public java.lang.String getCreatedId() {
      java.lang.Object ref = createdId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *创建人ID
     * </pre>
     *
     * <code>string createdId = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedIdBytes() {
      java.lang.Object ref = createdId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *创建人ID
     * </pre>
     *
     * <code>string createdId = 9;</code>
     */
    public Builder setCreatedId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建人ID
     * </pre>
     *
     * <code>string createdId = 9;</code>
     */
    public Builder clearCreatedId() {
      
      createdId_ = getDefaultInstance().getCreatedId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建人ID
     * </pre>
     *
     * <code>string createdId = 9;</code>
     */
    public Builder setCreatedIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object createdName_ = "";
    /**
     * <pre>
     *创建人姓名
     * </pre>
     *
     * <code>string createdName = 10;</code>
     */
    public java.lang.String getCreatedName() {
      java.lang.Object ref = createdName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        createdName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *创建人姓名
     * </pre>
     *
     * <code>string createdName = 10;</code>
     */
    public com.google.protobuf.ByteString
        getCreatedNameBytes() {
      java.lang.Object ref = createdName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        createdName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *创建人姓名
     * </pre>
     *
     * <code>string createdName = 10;</code>
     */
    public Builder setCreatedName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      createdName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建人姓名
     * </pre>
     *
     * <code>string createdName = 10;</code>
     */
    public Builder clearCreatedName() {
      
      createdName_ = getDefaultInstance().getCreatedName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建人姓名
     * </pre>
     *
     * <code>string createdName = 10;</code>
     */
    public Builder setCreatedNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      createdName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object ctime_ = "";
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string ctime = 11;</code>
     */
    public java.lang.String getCtime() {
      java.lang.Object ref = ctime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ctime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string ctime = 11;</code>
     */
    public com.google.protobuf.ByteString
        getCtimeBytes() {
      java.lang.Object ref = ctime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ctime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string ctime = 11;</code>
     */
    public Builder setCtime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ctime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string ctime = 11;</code>
     */
    public Builder clearCtime() {
      
      ctime_ = getDefaultInstance().getCtime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *创建时间
     * </pre>
     *
     * <code>string ctime = 11;</code>
     */
    public Builder setCtimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ctime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updatedId_ = "";
    /**
     * <pre>
     *更新人ID
     * </pre>
     *
     * <code>string updatedId = 12;</code>
     */
    public java.lang.String getUpdatedId() {
      java.lang.Object ref = updatedId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *更新人ID
     * </pre>
     *
     * <code>string updatedId = 12;</code>
     */
    public com.google.protobuf.ByteString
        getUpdatedIdBytes() {
      java.lang.Object ref = updatedId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *更新人ID
     * </pre>
     *
     * <code>string updatedId = 12;</code>
     */
    public Builder setUpdatedId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updatedId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *更新人ID
     * </pre>
     *
     * <code>string updatedId = 12;</code>
     */
    public Builder clearUpdatedId() {
      
      updatedId_ = getDefaultInstance().getUpdatedId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *更新人ID
     * </pre>
     *
     * <code>string updatedId = 12;</code>
     */
    public Builder setUpdatedIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updatedId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object updatedName_ = "";
    /**
     * <pre>
     *更新人姓名
     * </pre>
     *
     * <code>string updatedName = 13;</code>
     */
    public java.lang.String getUpdatedName() {
      java.lang.Object ref = updatedName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        updatedName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *更新人姓名
     * </pre>
     *
     * <code>string updatedName = 13;</code>
     */
    public com.google.protobuf.ByteString
        getUpdatedNameBytes() {
      java.lang.Object ref = updatedName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        updatedName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *更新人姓名
     * </pre>
     *
     * <code>string updatedName = 13;</code>
     */
    public Builder setUpdatedName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      updatedName_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *更新人姓名
     * </pre>
     *
     * <code>string updatedName = 13;</code>
     */
    public Builder clearUpdatedName() {
      
      updatedName_ = getDefaultInstance().getUpdatedName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *更新人姓名
     * </pre>
     *
     * <code>string updatedName = 13;</code>
     */
    public Builder setUpdatedNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      updatedName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object utime_ = "";
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string utime = 14;</code>
     */
    public java.lang.String getUtime() {
      java.lang.Object ref = utime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        utime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string utime = 14;</code>
     */
    public com.google.protobuf.ByteString
        getUtimeBytes() {
      java.lang.Object ref = utime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        utime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string utime = 14;</code>
     */
    public Builder setUtime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      utime_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string utime = 14;</code>
     */
    public Builder clearUtime() {
      
      utime_ = getDefaultInstance().getUtime();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *更新时间
     * </pre>
     *
     * <code>string utime = 14;</code>
     */
    public Builder setUtimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      utime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object version_ = "";
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string version = 15;</code>
     */
    public java.lang.String getVersion() {
      java.lang.Object ref = version_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        version_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string version = 15;</code>
     */
    public com.google.protobuf.ByteString
        getVersionBytes() {
      java.lang.Object ref = version_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        version_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string version = 15;</code>
     */
    public Builder setVersion(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      version_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string version = 15;</code>
     */
    public Builder clearVersion() {
      
      version_ = getDefaultInstance().getVersion();
      onChanged();
      return this;
    }
    /**
     * <pre>
     *版本
     * </pre>
     *
     * <code>string version = 15;</code>
     */
    public Builder setVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      version_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.topsec.mobiapi.proto.FileInfo)
  }

  // @@protoc_insertion_point(class_scope:com.topsec.mobiapi.proto.FileInfo)
  private static final com.topsec.mobiapi.proto.FileInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.topsec.mobiapi.proto.FileInfo();
  }

  public static com.topsec.mobiapi.proto.FileInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FileInfo>
      PARSER = new com.google.protobuf.AbstractParser<FileInfo>() {
    public FileInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FileInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FileInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FileInfo> getParserForType() {
    return PARSER;
  }

  public com.topsec.mobiapi.proto.FileInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

