// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileManage.proto

package com.topsec.mobiapi.proto;

public interface FileQueryRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.topsec.mobiapi.proto.FileQueryRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string searchCondition = 1;</code>
   */
  java.lang.String getSearchCondition();
  /**
   * <code>string searchCondition = 1;</code>
   */
  com.google.protobuf.ByteString
      getSearchConditionBytes();

  /**
   * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
   */
  int getTimesValue();
  /**
   * <code>.com.topsec.mobiapi.proto.FileQueryRequest.Times times = 2;</code>
   */
  com.topsec.mobiapi.proto.FileQueryRequest.Times getTimes();

  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
   */
  boolean hasPageContent();
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent();
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 3;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder();
}
