// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileManage.proto

package com.topsec.mobiapi.proto;

/**
 * Protobuf type {@code com.topsec.mobiapi.proto.GetFileInfoResponse}
 */
public  final class GetFileInfoResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.topsec.mobiapi.proto.GetFileInfoResponse)
    GetFileInfoResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetFileInfoResponse.newBuilder() to construct.
  private GetFileInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetFileInfoResponse() {
    fileList_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetFileInfoResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder subBuilder = null;
            if (baseResponse_ != null) {
              subBuilder = baseResponse_.toBuilder();
            }
            baseResponse_ = input.readMessage(com.topsec.mobiapi.proto.BaseMessage.BaseResponse.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(baseResponse_);
              baseResponse_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder subBuilder = null;
            if (pageContent_ != null) {
              subBuilder = pageContent_.toBuilder();
            }
            pageContent_ = input.readMessage(com.topsec.mobiapi.proto.BaseMessage.PageContent.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pageContent_);
              pageContent_ = subBuilder.buildPartial();
            }

            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              fileList_ = new java.util.ArrayList<com.topsec.mobiapi.proto.FileInfo>();
              mutable_bitField0_ |= 0x00000004;
            }
            fileList_.add(
                input.readMessage(com.topsec.mobiapi.proto.FileInfo.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        fileList_ = java.util.Collections.unmodifiableList(fileList_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.topsec.mobiapi.proto.GetFileInfoResponse.class, com.topsec.mobiapi.proto.GetFileInfoResponse.Builder.class);
  }

  private int bitField0_;
  public static final int BASERESPONSE_FIELD_NUMBER = 1;
  private com.topsec.mobiapi.proto.BaseMessage.BaseResponse baseResponse_;
  /**
   * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
   */
  public boolean hasBaseResponse() {
    return baseResponse_ != null;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.BaseResponse getBaseResponse() {
    return baseResponse_ == null ? com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance() : baseResponse_;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder getBaseResponseOrBuilder() {
    return getBaseResponse();
  }

  public static final int PAGECONTENT_FIELD_NUMBER = 2;
  private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_;
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public boolean hasPageContent() {
    return pageContent_ != null;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
    return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
  }
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
    return getPageContent();
  }

  public static final int FILELIST_FIELD_NUMBER = 3;
  private java.util.List<com.topsec.mobiapi.proto.FileInfo> fileList_;
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  public java.util.List<com.topsec.mobiapi.proto.FileInfo> getFileListList() {
    return fileList_;
  }
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  public java.util.List<? extends com.topsec.mobiapi.proto.FileInfoOrBuilder> 
      getFileListOrBuilderList() {
    return fileList_;
  }
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  public int getFileListCount() {
    return fileList_.size();
  }
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  public com.topsec.mobiapi.proto.FileInfo getFileList(int index) {
    return fileList_.get(index);
  }
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  public com.topsec.mobiapi.proto.FileInfoOrBuilder getFileListOrBuilder(
      int index) {
    return fileList_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (baseResponse_ != null) {
      output.writeMessage(1, getBaseResponse());
    }
    if (pageContent_ != null) {
      output.writeMessage(2, getPageContent());
    }
    for (int i = 0; i < fileList_.size(); i++) {
      output.writeMessage(3, fileList_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (baseResponse_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBaseResponse());
    }
    if (pageContent_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPageContent());
    }
    for (int i = 0; i < fileList_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, fileList_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.topsec.mobiapi.proto.GetFileInfoResponse)) {
      return super.equals(obj);
    }
    com.topsec.mobiapi.proto.GetFileInfoResponse other = (com.topsec.mobiapi.proto.GetFileInfoResponse) obj;

    boolean result = true;
    result = result && (hasBaseResponse() == other.hasBaseResponse());
    if (hasBaseResponse()) {
      result = result && getBaseResponse()
          .equals(other.getBaseResponse());
    }
    result = result && (hasPageContent() == other.hasPageContent());
    if (hasPageContent()) {
      result = result && getPageContent()
          .equals(other.getPageContent());
    }
    result = result && getFileListList()
        .equals(other.getFileListList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBaseResponse()) {
      hash = (37 * hash) + BASERESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getBaseResponse().hashCode();
    }
    if (hasPageContent()) {
      hash = (37 * hash) + PAGECONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getPageContent().hashCode();
    }
    if (getFileListCount() > 0) {
      hash = (37 * hash) + FILELIST_FIELD_NUMBER;
      hash = (53 * hash) + getFileListList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.topsec.mobiapi.proto.GetFileInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.topsec.mobiapi.proto.GetFileInfoResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.topsec.mobiapi.proto.GetFileInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.topsec.mobiapi.proto.GetFileInfoResponse)
      com.topsec.mobiapi.proto.GetFileInfoResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.topsec.mobiapi.proto.GetFileInfoResponse.class, com.topsec.mobiapi.proto.GetFileInfoResponse.Builder.class);
    }

    // Construct using com.topsec.mobiapi.proto.GetFileInfoResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getFileListFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (baseResponseBuilder_ == null) {
        baseResponse_ = null;
      } else {
        baseResponse_ = null;
        baseResponseBuilder_ = null;
      }
      if (pageContentBuilder_ == null) {
        pageContent_ = null;
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }
      if (fileListBuilder_ == null) {
        fileList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        fileListBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.topsec.mobiapi.proto.FileManage.internal_static_com_topsec_mobiapi_proto_GetFileInfoResponse_descriptor;
    }

    public com.topsec.mobiapi.proto.GetFileInfoResponse getDefaultInstanceForType() {
      return com.topsec.mobiapi.proto.GetFileInfoResponse.getDefaultInstance();
    }

    public com.topsec.mobiapi.proto.GetFileInfoResponse build() {
      com.topsec.mobiapi.proto.GetFileInfoResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.topsec.mobiapi.proto.GetFileInfoResponse buildPartial() {
      com.topsec.mobiapi.proto.GetFileInfoResponse result = new com.topsec.mobiapi.proto.GetFileInfoResponse(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (baseResponseBuilder_ == null) {
        result.baseResponse_ = baseResponse_;
      } else {
        result.baseResponse_ = baseResponseBuilder_.build();
      }
      if (pageContentBuilder_ == null) {
        result.pageContent_ = pageContent_;
      } else {
        result.pageContent_ = pageContentBuilder_.build();
      }
      if (fileListBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          fileList_ = java.util.Collections.unmodifiableList(fileList_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.fileList_ = fileList_;
      } else {
        result.fileList_ = fileListBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.topsec.mobiapi.proto.GetFileInfoResponse) {
        return mergeFrom((com.topsec.mobiapi.proto.GetFileInfoResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.topsec.mobiapi.proto.GetFileInfoResponse other) {
      if (other == com.topsec.mobiapi.proto.GetFileInfoResponse.getDefaultInstance()) return this;
      if (other.hasBaseResponse()) {
        mergeBaseResponse(other.getBaseResponse());
      }
      if (other.hasPageContent()) {
        mergePageContent(other.getPageContent());
      }
      if (fileListBuilder_ == null) {
        if (!other.fileList_.isEmpty()) {
          if (fileList_.isEmpty()) {
            fileList_ = other.fileList_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureFileListIsMutable();
            fileList_.addAll(other.fileList_);
          }
          onChanged();
        }
      } else {
        if (!other.fileList_.isEmpty()) {
          if (fileListBuilder_.isEmpty()) {
            fileListBuilder_.dispose();
            fileListBuilder_ = null;
            fileList_ = other.fileList_;
            bitField0_ = (bitField0_ & ~0x00000004);
            fileListBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getFileListFieldBuilder() : null;
          } else {
            fileListBuilder_.addAllMessages(other.fileList_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.topsec.mobiapi.proto.GetFileInfoResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.topsec.mobiapi.proto.GetFileInfoResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.topsec.mobiapi.proto.BaseMessage.BaseResponse baseResponse_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder, com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder> baseResponseBuilder_;
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public boolean hasBaseResponse() {
      return baseResponseBuilder_ != null || baseResponse_ != null;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.BaseResponse getBaseResponse() {
      if (baseResponseBuilder_ == null) {
        return baseResponse_ == null ? com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance() : baseResponse_;
      } else {
        return baseResponseBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public Builder setBaseResponse(com.topsec.mobiapi.proto.BaseMessage.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        baseResponse_ = value;
        onChanged();
      } else {
        baseResponseBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public Builder setBaseResponse(
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder builderForValue) {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = builderForValue.build();
        onChanged();
      } else {
        baseResponseBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public Builder mergeBaseResponse(com.topsec.mobiapi.proto.BaseMessage.BaseResponse value) {
      if (baseResponseBuilder_ == null) {
        if (baseResponse_ != null) {
          baseResponse_ =
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse.newBuilder(baseResponse_).mergeFrom(value).buildPartial();
        } else {
          baseResponse_ = value;
        }
        onChanged();
      } else {
        baseResponseBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public Builder clearBaseResponse() {
      if (baseResponseBuilder_ == null) {
        baseResponse_ = null;
        onChanged();
      } else {
        baseResponse_ = null;
        baseResponseBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder getBaseResponseBuilder() {
      
      onChanged();
      return getBaseResponseFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder getBaseResponseOrBuilder() {
      if (baseResponseBuilder_ != null) {
        return baseResponseBuilder_.getMessageOrBuilder();
      } else {
        return baseResponse_ == null ?
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse.getDefaultInstance() : baseResponse_;
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.BaseResponse, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder, com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder> 
        getBaseResponseFieldBuilder() {
      if (baseResponseBuilder_ == null) {
        baseResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.topsec.mobiapi.proto.BaseMessage.BaseResponse, com.topsec.mobiapi.proto.BaseMessage.BaseResponse.Builder, com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder>(
                getBaseResponse(),
                getParentForChildren(),
                isClean());
        baseResponse_ = null;
      }
      return baseResponseBuilder_;
    }

    private com.topsec.mobiapi.proto.BaseMessage.PageContent pageContent_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> pageContentBuilder_;
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public boolean hasPageContent() {
      return pageContentBuilder_ != null || pageContent_ != null;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent() {
      if (pageContentBuilder_ == null) {
        return pageContent_ == null ? com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      } else {
        return pageContentBuilder_.getMessage();
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder setPageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pageContent_ = value;
        onChanged();
      } else {
        pageContentBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder setPageContent(
        com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder builderForValue) {
      if (pageContentBuilder_ == null) {
        pageContent_ = builderForValue.build();
        onChanged();
      } else {
        pageContentBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder mergePageContent(com.topsec.mobiapi.proto.BaseMessage.PageContent value) {
      if (pageContentBuilder_ == null) {
        if (pageContent_ != null) {
          pageContent_ =
            com.topsec.mobiapi.proto.BaseMessage.PageContent.newBuilder(pageContent_).mergeFrom(value).buildPartial();
        } else {
          pageContent_ = value;
        }
        onChanged();
      } else {
        pageContentBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public Builder clearPageContent() {
      if (pageContentBuilder_ == null) {
        pageContent_ = null;
        onChanged();
      } else {
        pageContent_ = null;
        pageContentBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder getPageContentBuilder() {
      
      onChanged();
      return getPageContentFieldBuilder().getBuilder();
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    public com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder() {
      if (pageContentBuilder_ != null) {
        return pageContentBuilder_.getMessageOrBuilder();
      } else {
        return pageContent_ == null ?
            com.topsec.mobiapi.proto.BaseMessage.PageContent.getDefaultInstance() : pageContent_;
      }
    }
    /**
     * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder> 
        getPageContentFieldBuilder() {
      if (pageContentBuilder_ == null) {
        pageContentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.topsec.mobiapi.proto.BaseMessage.PageContent, com.topsec.mobiapi.proto.BaseMessage.PageContent.Builder, com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder>(
                getPageContent(),
                getParentForChildren(),
                isClean());
        pageContent_ = null;
      }
      return pageContentBuilder_;
    }

    private java.util.List<com.topsec.mobiapi.proto.FileInfo> fileList_ =
      java.util.Collections.emptyList();
    private void ensureFileListIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        fileList_ = new java.util.ArrayList<com.topsec.mobiapi.proto.FileInfo>(fileList_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.topsec.mobiapi.proto.FileInfo, com.topsec.mobiapi.proto.FileInfo.Builder, com.topsec.mobiapi.proto.FileInfoOrBuilder> fileListBuilder_;

    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public java.util.List<com.topsec.mobiapi.proto.FileInfo> getFileListList() {
      if (fileListBuilder_ == null) {
        return java.util.Collections.unmodifiableList(fileList_);
      } else {
        return fileListBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public int getFileListCount() {
      if (fileListBuilder_ == null) {
        return fileList_.size();
      } else {
        return fileListBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public com.topsec.mobiapi.proto.FileInfo getFileList(int index) {
      if (fileListBuilder_ == null) {
        return fileList_.get(index);
      } else {
        return fileListBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder setFileList(
        int index, com.topsec.mobiapi.proto.FileInfo value) {
      if (fileListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileListIsMutable();
        fileList_.set(index, value);
        onChanged();
      } else {
        fileListBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder setFileList(
        int index, com.topsec.mobiapi.proto.FileInfo.Builder builderForValue) {
      if (fileListBuilder_ == null) {
        ensureFileListIsMutable();
        fileList_.set(index, builderForValue.build());
        onChanged();
      } else {
        fileListBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder addFileList(com.topsec.mobiapi.proto.FileInfo value) {
      if (fileListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileListIsMutable();
        fileList_.add(value);
        onChanged();
      } else {
        fileListBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder addFileList(
        int index, com.topsec.mobiapi.proto.FileInfo value) {
      if (fileListBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureFileListIsMutable();
        fileList_.add(index, value);
        onChanged();
      } else {
        fileListBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder addFileList(
        com.topsec.mobiapi.proto.FileInfo.Builder builderForValue) {
      if (fileListBuilder_ == null) {
        ensureFileListIsMutable();
        fileList_.add(builderForValue.build());
        onChanged();
      } else {
        fileListBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder addFileList(
        int index, com.topsec.mobiapi.proto.FileInfo.Builder builderForValue) {
      if (fileListBuilder_ == null) {
        ensureFileListIsMutable();
        fileList_.add(index, builderForValue.build());
        onChanged();
      } else {
        fileListBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder addAllFileList(
        java.lang.Iterable<? extends com.topsec.mobiapi.proto.FileInfo> values) {
      if (fileListBuilder_ == null) {
        ensureFileListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, fileList_);
        onChanged();
      } else {
        fileListBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder clearFileList() {
      if (fileListBuilder_ == null) {
        fileList_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        fileListBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public Builder removeFileList(int index) {
      if (fileListBuilder_ == null) {
        ensureFileListIsMutable();
        fileList_.remove(index);
        onChanged();
      } else {
        fileListBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public com.topsec.mobiapi.proto.FileInfo.Builder getFileListBuilder(
        int index) {
      return getFileListFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public com.topsec.mobiapi.proto.FileInfoOrBuilder getFileListOrBuilder(
        int index) {
      if (fileListBuilder_ == null) {
        return fileList_.get(index);  } else {
        return fileListBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public java.util.List<? extends com.topsec.mobiapi.proto.FileInfoOrBuilder> 
         getFileListOrBuilderList() {
      if (fileListBuilder_ != null) {
        return fileListBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(fileList_);
      }
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public com.topsec.mobiapi.proto.FileInfo.Builder addFileListBuilder() {
      return getFileListFieldBuilder().addBuilder(
          com.topsec.mobiapi.proto.FileInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public com.topsec.mobiapi.proto.FileInfo.Builder addFileListBuilder(
        int index) {
      return getFileListFieldBuilder().addBuilder(
          index, com.topsec.mobiapi.proto.FileInfo.getDefaultInstance());
    }
    /**
     * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
     */
    public java.util.List<com.topsec.mobiapi.proto.FileInfo.Builder> 
         getFileListBuilderList() {
      return getFileListFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.topsec.mobiapi.proto.FileInfo, com.topsec.mobiapi.proto.FileInfo.Builder, com.topsec.mobiapi.proto.FileInfoOrBuilder> 
        getFileListFieldBuilder() {
      if (fileListBuilder_ == null) {
        fileListBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.topsec.mobiapi.proto.FileInfo, com.topsec.mobiapi.proto.FileInfo.Builder, com.topsec.mobiapi.proto.FileInfoOrBuilder>(
                fileList_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        fileList_ = null;
      }
      return fileListBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.topsec.mobiapi.proto.GetFileInfoResponse)
  }

  // @@protoc_insertion_point(class_scope:com.topsec.mobiapi.proto.GetFileInfoResponse)
  private static final com.topsec.mobiapi.proto.GetFileInfoResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.topsec.mobiapi.proto.GetFileInfoResponse();
  }

  public static com.topsec.mobiapi.proto.GetFileInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetFileInfoResponse>
      PARSER = new com.google.protobuf.AbstractParser<GetFileInfoResponse>() {
    public GetFileInfoResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetFileInfoResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetFileInfoResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetFileInfoResponse> getParserForType() {
    return PARSER;
  }

  public com.topsec.mobiapi.proto.GetFileInfoResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

