// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fileManage.proto

package com.topsec.mobiapi.proto;

public interface GetFileInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.topsec.mobiapi.proto.GetFileInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
   */
  boolean hasBaseResponse();
  /**
   * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.BaseResponse getBaseResponse();
  /**
   * <code>.com.topsec.mobiapi.proto.BaseResponse baseResponse = 1;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.BaseResponseOrBuilder getBaseResponseOrBuilder();

  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  boolean hasPageContent();
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContent getPageContent();
  /**
   * <code>.com.topsec.mobiapi.proto.PageContent pageContent = 2;</code>
   */
  com.topsec.mobiapi.proto.BaseMessage.PageContentOrBuilder getPageContentOrBuilder();

  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  java.util.List<com.topsec.mobiapi.proto.FileInfo> 
      getFileListList();
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  com.topsec.mobiapi.proto.FileInfo getFileList(int index);
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  int getFileListCount();
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  java.util.List<? extends com.topsec.mobiapi.proto.FileInfoOrBuilder> 
      getFileListOrBuilderList();
  /**
   * <code>repeated .com.topsec.mobiapi.proto.FileInfo fileList = 3;</code>
   */
  com.topsec.mobiapi.proto.FileInfoOrBuilder getFileListOrBuilder(
      int index);
}
