// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: channel.proto

package com.topsec.mobiapi.proto;

public interface TechnicanCertificateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.topsec.mobiapi.proto.TechnicanCertificate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *证书id
   * </pre>
   *
   * <code>string tcId = 1;</code>
   */
  java.lang.String getTcId();
  /**
   * <pre>
   *证书id
   * </pre>
   *
   * <code>string tcId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTcIdBytes();

  /**
   * <pre>
   *证书方向
   * </pre>
   *
   * <code>string tcDrt = 2;</code>
   */
  java.lang.String getTcDrt();
  /**
   * <pre>
   *证书方向
   * </pre>
   *
   * <code>string tcDrt = 2;</code>
   */
  com.google.protobuf.ByteString
      getTcDrtBytes();

  /**
   * <pre>
   *证书级别
   * </pre>
   *
   * <code>string tcLv = 3;</code>
   */
  java.lang.String getTcLv();
  /**
   * <pre>
   *证书级别
   * </pre>
   *
   * <code>string tcLv = 3;</code>
   */
  com.google.protobuf.ByteString
      getTcLvBytes();

  /**
   * <pre>
   *证书失效时间 yyyy-MM-dd
   * </pre>
   *
   * <code>string tcTime = 4;</code>
   */
  java.lang.String getTcTime();
  /**
   * <pre>
   *证书失效时间 yyyy-MM-dd
   * </pre>
   *
   * <code>string tcTime = 4;</code>
   */
  com.google.protobuf.ByteString
      getTcTimeBytes();
}
